In [2]:
import os
import polars as pl
import numpy as np
import torch
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time
from sqlalchemy import create_engine
import pymssql
from typing import List, Dict

import warnings
warnings.filterwarnings('ignore')

In [3]:
T,N = 3400, 5422
start_dt = '2008-01-01'     
end_dt = '2025-12-31'

JY_CONFIG = {
    "server": '10.10.0.102',
    "user": 'jydbReader',
    "password": 'jy@9043!Reader',
    "database": 'jydb',
    "charset": 'cp936'
}
JY_CONN = pymssql.connect(**JY_CONFIG)

ROOT = '/data/xujiayi/end2end/d_field/'

#### Basics

In [5]:
sql_axis = f'''select
                C.SecuCode as "tick",
                A.TradingDay as "date"
            from QT_StockPerformance A
            left join SecuMain C
            on A.InnerCode = C.InnerCode
            where A.TradingDay between '{start_dt}' and '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
            union all
            select
                C.SecuCode as "tick",
                B.TradingDay as "date"
            from LC_STIBPerformance B
            left join SecuMain C
            on B.InnerCode = C.InnerCode
            where B.TradingDay between '{start_dt}' and '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
        '''
axis = pl.read_database(sql_axis, JY_CONN).sort('tick','date')

dates = axis['date'].unique().sort().to_numpy()
#np.save('/data/xujiayi/end2end/axis/dates.npy', dts, allow_pickle=True)

ticks = axis['tick'].unique().sort().to_numpy()
#np.save('/data/xujiayi/end2end/axis/ticks.npy', ticks, allow_pickle=True)

In [4]:
sql_fuquan = f'''select
                   A.ExDiviDate as "date",
                   B.SecuCode as "tick",
                   A.AdjustingFactor as "fq_factor"
                from QT_StockAdjustFactor A
                left join SecuMain B
                on A.InnerCode = B.InnerCode
                union all
                select
                   C.ExDiviDate as "date",
                   B.SecuCode as "tick",
                   C.RatioAdjustingFactor as "fq_factor"
                from LC_STIBAdjustingFactor C
                left join SecuMain B
                on C.InnerCode = B.InnerCode
             '''
fuquan = pl.read_database(sql_fuquan, JY_CONN).sort('tick','date')
fuquan = axis.join(
    fuquan,
    how='left',
    on=['tick','date']
).with_columns(
    pl.col('fq_factor').forward_fill().over('tick')
)
fuquan = fuquan.pivot(index='date', columns='tick', values='fq_factor').fill_null(1)
fuquan = fuquan.drop('date').to_numpy().astype(float)

fuquan

array([[  1.      ,   1.      ,   1.      , ...,   1.      ,   1.      ,
          1.      ],
       [  1.      ,   1.      ,   1.      , ...,   1.      ,   1.      ,
          1.      ],
       [  1.      ,   1.      ,   1.      , ...,   1.      ,   1.      ,
          1.      ],
       ...,
       [154.496923, 116.819198,   1.      , ...,   1.      ,   1.093522,
          1.      ],
       [154.496923, 116.819198,   1.      , ...,   1.      ,   1.093522,
          1.      ],
       [154.496923, 116.819198,   1.      , ...,   1.      ,   1.093522,
          1.      ]], shape=(4376, 5436))

In [5]:
fuquan.tofile('/data/xujiayi/end2end/d_field/fuquan.bin')

In [ ]:
dates = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)
fuquan = np.memmap(f'/data/xujiayi/end2end/d_field/fuquan.bin',shape=(len(dates),len(ticks)), dtype=float, mode='r')
DAILY_FEATURES = ['open','high','low','close','volume']
for feat in DAILY_FEATURES:
    arr = np.memmap(f'/data/xujiayi/end2end/d_field/{feat}.bin',shape=(len(dates),len(ticks)), dtype=float, mode='r')
    arr_adj  = arr*fuquan
    print(arr_adj)
    arr_adj.astype(float).tofile(f'/data/xujiayi/end2end/d_field/{feat}_adj.bin')

[[  38.5          29.02          9.86       ...           nan
            nan           nan]
 [  38.           29.1          10.4        ...           nan
            nan           nan]
 [  37.4          28.6          10.8        ...           nan
            nan           nan]
 ...
 [1782.89449142  554.8911905    10.9        ...           nan
    37.13600712  123.        ]
 [1781.34952219  551.38661456   10.84       ...  265.6
    36.37054172  124.45      ]
 [1773.62467604  544.37746268   11.3        ...  240.
    36.4689587   125.99      ]]
[[  38.74         29.51         10.46       ...           nan
            nan           nan]
 [  38.08         29.1          10.68       ...           nan
            nan           nan]
 [  38.7          29.6          10.99       ...           nan
            nan           nan]
 ...
 [1795.25424526  559.56395842   11.2        ...           nan
    37.13600712  125.65      ]
 [1785.98442988  552.55480654   11.41       ...  276.82
    36.73140398  126.69      ]
 [1775.16964527  546.71384664   11.35       ...  276.57
    36.72046876  126.2       ]]
[[  37.65         28.39          9.71       ...           nan
            nan           nan]
 [  36.51         28.01         10.18       ...           nan
            nan           nan]
 [  37.38         28.23         10.45       ...           nan
            nan           nan]
 ...
 [1776.7146145   551.38661456   10.71       ...           nan
    36.28305996  122.02      ]
 [1768.98976835  539.70469476   10.73       ...  220.23
    35.98780902  124.        ]
 [1761.2649222   539.70469476   11.07       ...  235.03
    36.31586562  122.4       ]]
[[  37.98         29.19         10.4        ...           nan
            nan           nan]
 [  37.35         28.49         10.68       ...           nan
            nan           nan]
 [  38.37         29.24         10.82       ...           nan
            nan           nan]
 ...
 [1785.98442988  553.72299852   10.88       ...           nan
    36.61111656  122.5       ]
 [1773.62467604  539.70469476   11.27       ...  226.01
    36.61111656  125.28      ]
 [1762.80989143  543.2092707    11.08       ...  256.8
    36.32680084  122.83      ]]
[[2.00524730e+07 9.38796710e+07 5.07482500e+06 ...            nan
             nan            nan]
 [2.75648310e+07 9.72924110e+07 4.45350400e+06 ...            nan
             nan            nan]
 [1.98704380e+07 1.09093075e+08 3.46571900e+06 ...            nan
             nan            nan]
 ...
 [1.00159648e+10 1.40820297e+10 2.75900000e+06 ...            nan
  2.80005056e+06 5.06831610e+07]
 [9.00074864e+09 1.77257428e+10 4.09974200e+06 ... 1.80690460e+07
  2.04619946e+06 6.04958310e+07]
 [9.12490298e+09 1.25646203e+10 1.80560000e+06 ... 1.38074980e+07
  2.07061890e+06 4.11586850e+07]]

In [ ]:
fields = {
    'ClosePrice' : "close",
    'HighPrice' : "high",
    'LowPrice' : "low",
    'OpenPrice' : "open",
    "TurnoverVolume": 'volume',
    'TurnoverValue' : "amount",
    'TurnoverRate' : "turnover",
}

for k, v in tqdm(fields.items()):
    sql_field = f'''select
                        C.SecuCode as "tick",
                        A.TradingDay as "date",
                        A.{k} as "{v}"
                    from QT_StockPerformance A
                    left join SecuMain C
                    on A.InnerCode = C.InnerCode
                    where A.TradingDay between '{start_dt}' and '{end_dt}'
                        and C.SecuMarket in (83,90)
                        and C.SecuCategory=1
                    union all
                    select
                        C.SecuCode as "tick",
                        B.TradingDay as "date",
                        B.{k} as "{v}"
                    from LC_STIBPerformance B
                    left join SecuMain C
                    on B.InnerCode = C.InnerCode
                    where B.TradingDay between '{start_dt}' and '{end_dt}'
                        and C.SecuMarket in (83,90)
                        and C.SecuCategory=1
                 '''
    d_field = pl.read_database(sql_field, JY_CONN).sort('tick','date')
    d_field = d_field.pivot(index='date', columns='tick', values=v).drop('date').to_numpy().astype(float)
    if v=='amount' or v=='turnover':
        d_field.tofile(f"/data/xujiayi/end2end/d_field/{v}.bin")
    else:
        d_field.tofile(f"/data/xujiayi/end2end/d_field/{v}.bin")
        d_field_adj = d_field*fuquan
        d_field_adj.tofile(f"/data/xujiayi/end2end/d_field/{v}_adj.bin")

In [ ]:
sql_pct = f'''select
                        C.SecuCode as "tick",
                        A.TradingDay as "date",
                        A.ChangePCT as "pct"
                    from QT_StockPerformance A
                    left join SecuMain C
                    on A.InnerCode = C.InnerCode
                    where A.TradingDay between '2007-01-01' and '2026-03-01'
                        and C.SecuMarket in (83,90)
                        and C.SecuCategory=1
                    union all
                    select
                        C.SecuCode as "tick",
                        B.TradingDay as "date",
                        B.ChangePCT as "pct"
                    from LC_STIBPerformance B
                    left join SecuMain C
                    on B.InnerCode = C.InnerCode
                    where B.TradingDay between '2007-01-01' and '2026-03-01'
                        and C.SecuMarket in (83,90)
                        and C.SecuCategory=1
            '''
pct = pl.read_database(sql_pct, JY_CONN).sort('tick','date')
pct = pct.pivot(index='date', columns='tick', values='pct').to_pandas().set_index('date')
pct = pct.shift(-1)
pct = pct/100
pct = pct.reindex(index=dates, columns=ticks)
pct.values.astype(float).tofile('/data/xujiayi/end2end/label/Y.1D.bin')

In [ ]:
#pct = pct.values.astype(float)
industry_mask = np.memmap('/data/xujiayi/end2end/mask/industry.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
logmv = np.memmap('/data/xujiayi/end2end/d_field/logmv.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')

from ..utils import Calculator, Processor
for i in [1,3,5,10]:
    y = Calculator.rolling_retprod(pct,i,True)
    y.astype(float).tofile(f'/data/xujiayi/end2end/label/Y.{i}D.bin')
    y_yeo = Processor.yeojohnson(y)
    y_yeo.astype(float).tofile(f'/data/xujiayi/end2end/label/Yyeo.{i}D.bin')
    y_z = Processor.cross_standardize(y)
    y_z.astype(float).tofile(f'/data/xujiayi/end2end/label/Yz.{i}D.bin')
    y_dm = Processor.indmv_neutral_longshort(y, industry_mask, logmv)
    y_dm.astype(float).tofile(f'/data/xujiayi/end2end/label/Ydm.{i}D.bin')
    y_r = Processor.rank_transform(y)
    y_r.astype(float).tofile(f'/data/xujiayi/end2end/label/Yr.{i}D.bin')
    y_ls = Processor.winsorize_linearsmooth(y)
    y_ls.astype(float).tofile(f'/data/xujiayi/end2end/label/Yls.{i}D.bin')

In [18]:
sql_ceil_floor = f'''
    select
        A.TradingDay as 'date',
        B.SecuCode as 'tick',
        A.PriceCeiling as "ceil",
        A.PriceFloor as "floor"
    from QT_PriceLimit A
    left join SecuMain B on A.InnerCode = B.InnerCode
    where A.TradingDay between '{start_dt}' and '{end_dt}'
        and B.SecuMarket in (83,90)
        and B.SecuCategory=1
    '''
hitprice_df = pl.read_database(sql_ceil_floor, JY_CONN).sort('tick','date')
ceil = hitprice_df.pivot(index='date', columns='tick', values='ceil').to_pandas().set_index('date').reindex(columns=ticks)
floor = hitprice_df.pivot(index='date', columns='tick', values='floor').to_pandas().set_index('date').reindex(columns=ticks)

In [20]:
fuquan = np.memmap('/data/xujiayi/end2end/d_field/fuquan.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')

ceil.values.astype(float).tofile(f"/data/xujiayi/end2end/d_field/ceil.bin")
ceil_adj = ceil.values.astype(float)*fuquan
ceil_adj.astype(float).tofile(f"/data/xujiayi/end2end/d_field/ceil_adj.bin")

floor.values.astype(float).tofile(f"/data/xujiayi/end2end/d_field/floor.bin")
floor_adj = floor.values.astype(float)*fuquan
floor_adj.astype(float).tofile(f"/data/xujiayi/end2end/d_field/floor_adj.bin")

In [ ]:
def get_next_trading_day(date) -> str:
    date_dt = datetime.strptime(date, "%Y-%m-%d")
    # 读取全市场交易日历（只需查一次，可优化为全局缓存）
    sql_trading_days = """
    SELECT DISTINCT TradingDay as date
    FROM QT_StockPerformance
    WHERE TradingDay >= DATEADD(day, 1, '{date}')
    ORDER BY TradingDay ASC
    """
    trading_days_df = pl.read_database(sql_trading_days.format(date=date), JY_CONN)
    if trading_days_df.height == 0:
        return date  # 无后续交易日，返回原日期
    next_day = trading_days_df["date"][0]
    return datetime.strftime(next_day, "%Y-%m-%d")


def is_st(date, listed_ticks) -> bool:
    """是否ST股"""
    listed_ticks_str = ",".join([f"'{t}'" for t in listed_ticks])

    sql_isst = f'''
    select distinct B.SecuCode as tick, A.SpecialTradeType as "type"
    from LC_SpecialTrade A
    left join SecuMain B on A.InnerCode = B.InnerCode
    where A.InfoPublDate = '{date}' and B.SecuCode in ({listed_ticks_str})
    union all
    select distinct B.SecuCode as tick, C.ChangeType as "type"
    from LC_STIBSecuChange C
    left join SecuMain B on C.InnerCode = B.InnerCode
    where C.InfoPublDate = '{date}' and B.SecuCode in ({listed_ticks_str})
    '''
    st_df = pl.read_database(sql_isst, JY_CONN)
    # 筛选有效ST记录，提取ST股票代码集合
    st_tick_set = set(st_df.filter(pl.col("type").is_not_null())["tick"].to_list())
    return np.array([tick in st_tick_set for tick in listed_ticks])


def is_suspend(date, listed_ticks) -> bool:
    """是否停牌"""
    listed_ticks_str = ",".join([f"'{t}'" for t in listed_ticks])

    sql_suspend = f'''
    select distinct C.SecuCode as tick, A.Ifsuspend as "is_suspend"
    from QT_StockPerformance A
    left join SecuMain C on A.InnerCode = C.InnerCode
    where A.TradingDay = '{date}' and C.SecuCode in ({listed_ticks_str}) and C.SecuMarket in (83,90) and C.SecuCategory=1
    union all
    select distinct C.SecuCode as tick, B.Ifsuspend as "is_suspend"
    from LC_STIBPerformance B
    left join SecuMain C on B.InnerCode = C.InnerCode
    where B.TradingDay = '{date}' and C.SecuCode in ({listed_ticks_str}) and C.SecuMarket in (83,90) and C.SecuCategory=1
    '''
    suspend_df = pl.read_database(sql_suspend, JY_CONN)
    if suspend_df.height == 0:
        # 无数据默认停牌
        return [True for _ in listed_ticks]
    # 构建{股票代码: 是否停牌}字典
    suspend_dict = dict(zip(suspend_df["tick"], suspend_df["is_suspend"].fill_null(1).to_list()))
    # 按输入顺序返回，未查到的股票默认停牌
    return [suspend_dict.get(tick, 1) == 1 for tick in listed_ticks]


def is_new(date, listed_ticks) -> bool:
    """是否上市不满240天"""
    listed_ticks_str = ",".join([f"'{t}'" for t in listed_ticks])

    sql_listdate = f'''
    select SecuCode as tick, COALESCE(ListedDate, '1900-01-01') as "list_date"
    from SecuMain
    where SecuCode in ({listed_ticks_str}) and SecuMarket in (83,90) and SecuCategory=1
    '''
    list_df = pl.read_database(sql_listdate, JY_CONN)
    list_dict = dict(zip(list_df["tick"], list_df["list_date"].to_list())) if list_df.height > 0 else {}
    date_dt = datetime.strptime(date, "%Y-%m-%d")
    return [
        True if tick not in list_dict
        else list_dict[tick] == '1900-01-01'
             or (date_dt - list_dict[tick]).days < 242
        for tick in listed_ticks
    ]


def is_hit_ceil_floor(date, listed_ticks) -> (bool, bool):
    """是否涨停/跌停"""
    listed_ticks_str = ",".join([f"'{t}'" for t in listed_ticks])

    sql_hit = f'''
    select distinct B.SecuCode as tick, A.StockBoard as "hit_ceil", A.LimitBoard as "hit_floor"
    from QT_PerformanceData A
    left join SecuMain B on A.InnerCode = B.InnerCode
    where A.TradingDay = '{date}' and B.SecuCode in ({listed_ticks_str}) and B.SecuMarket in (83,90) and B.SecuCategory=1
    union all
    select distinct B.SecuCode as tick, C.StockBoard as "hit_ceil", C.LimitBoard as "hit_floor"
    from LC_STIBPerformanceData C
    left join SecuMain B on C.InnerCode = B.InnerCode
    where C.TradingDay = '{date}' and B.SecuCode in ({listed_ticks_str}) and B.SecuMarket in (83,90) and B.SecuCategory=1
    '''
    hit_df = pl.read_database(sql_hit, JY_CONN)
    # 无数据直接返回全False数组
    if hit_df.height == 0:
        return [False] * len(listed_ticks), [False] * len(listed_ticks)

    hit_df = hit_df.with_columns([
        pl.col("hit_ceil").fill_null(0).cast(pl.Int8).eq(1).alias("is_ceil"),
        pl.col("hit_floor").fill_null(0).cast(pl.Int8).eq(1).alias("is_floor")
    ])

    hit_dict = hit_df.select(["tick", "is_ceil", "is_floor"]).to_dict(as_series=False)
    hit_map = dict(zip(hit_dict["tick"], zip(hit_dict["is_ceil"], hit_dict["is_floor"])))

    hit_ceil_list = [hit_map.get(tick, (False, False))[0] for tick in listed_ticks]
    hit_floor_list = [hit_map.get(tick, (False, False))[1] for tick in listed_ticks]
    return hit_ceil_list, hit_floor_list


def is_non_trade(date, listed_ticks) -> bool:
    """是否无成交"""
    listed_ticks_str = ",".join([f"'{t}'" for t in listed_ticks])

    sql_nontrade = f'''
    select distinct B.SecuCode as tick, A.TurnoverVolume as "volume"
    from QT_Performance A
    left join SecuMain B on A.InnerCode = B.InnerCode
    where A.TradingDay = '{date}' and B.SecuCode in ({listed_ticks_str}) and B.SecuMarket in (83,90) and B.SecuCategory=1
    union all
    select distinct B.SecuCode as tick, C.TurnoverVolume as "volume"
    from LC_STIBPerformance C
    left join SecuMain B on C.InnerCode = B.InnerCode
    where C.TradingDay = '{date}' and B.SecuCode in ({listed_ticks_str}) and B.SecuMarket in (83,90) and B.SecuCategory=1
    '''
    trade_df = pl.read_database(sql_nontrade, JY_CONN)
    if trade_df.height == 0:
        # 无数据默认无成交
        return [True for _ in listed_ticks]
    # 构建{股票代码: 成交量}字典
    volume_dict = dict(zip(trade_df["tick"], trade_df["volume"].fill_null(0).to_list()))
    # 按输入顺序返回，未查到的股票默认无成交
    return [volume_dict.get(tick, 0) == 0 for tick in listed_ticks]


def is_tradable(date, listed_ticks):
    st = np.array(is_st(date, listed_ticks))
    new = np.array(is_new(date, listed_ticks))
    suspend = np.array(is_suspend(date, listed_ticks))
    non_trade_today = np.array(is_non_trade(date, listed_ticks))
    hit_ceil_today, hit_floor_today = is_hit_ceil_floor(date, listed_ticks)
    hit_ceil_today = np.array(hit_ceil_today)
    hit_floor_today = np.array(hit_floor_today)

    next_date = get_next_trading_day(date)
    non_trade_next = np.array(is_non_trade(next_date, listed_ticks))
    hit_ceil_next, hit_floor_next = is_hit_ceil_floor(next_date, listed_ticks)
    hit_ceil_next = np.array(hit_ceil_next)
    hit_floor_next = np.array(hit_floor_next)

    tradable = ~(
            st | new | suspend |
            non_trade_today | hit_ceil_today | hit_floor_today |
            non_trade_next | hit_ceil_next | hit_floor_next
    )

    return tradable


tradables = []
dates = pd.to_datetime(dates).strftime('%Y-%m-%d')
for date in tqdm(dates):
    tradable = is_tradable(date,ticks)
    tradables.append(tradable)
tradables = np.stack(tradables)
print(tradables)
tradables.astype(bool).tofile(f'/data/xujiayi/end2end/mask/tradable.bin')

In [7]:
tradable = np.memmap('/data/xujiayi/end2end/mask/tradable.bin',shape=(len(dates),len(ticks)), mode='r', dtype=bool)
tradable

memmap([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False],
        ...,
        [ True,  True,  True, ..., False,  True,  True],
        [ True,  True,  True, ..., False,  True,  True],
        [ True,  True,  True, ..., False,  True,  True]],
       shape=(4376, 5436))

#### Industry_Mask

In [52]:
sql = f'''
select
   A.InfoPublDate   as 'start_date',
   A.CancelDate     as 'end_date',
   B.SecuCode       as 'tick',
   B.CompanyCode    as 'code',
   A.FirstIndustryName as 'industry'
from DZ_ExgIndustry A
left join SecuMain B
on A.CompanyCode = B.CompanyCode
where A.Standard=38
   and B.SecuMarket in (83,90)
   and B.SecuCategory=1

union all 

select
   C.InfoPublDate   as 'start_date',
   C.CancelDate     as 'end_date',
   B.SecuCode       as 'tick',
   B.CompanyCode    as 'code',
   C.FirstIndustryName as 'industry'
from LC_STIBExgIndustry C
left join SecuMain B
on C.CompanyCode = B.CompanyCode
where C.Standard=38
   and B.SecuMarket in (83,90)
   and B.SecuCategory=1
'''

ind = pl.read_database(sql, JY_CONN).sort('tick')
ind

shape: (16_280, 5)
┌─────────────────────┬─────────────────────┬────────┬──────────┬──────────┐
│ start_date          ┆ end_date            ┆ tick   ┆ code     ┆ industry │
│ ---                 ┆ ---                 ┆ ---    ┆ ---      ┆ ---      │
│ datetime[μs]        ┆ datetime[μs]        ┆ str    ┆ i64      ┆ str      │
╞═════════════════════╪═════════════════════╪════════╪══════════╪══════════╡
│ 1991-04-03 00:00:00 ┆ 2014-01-01 00:00:00 ┆ 000001 ┆ 3        ┆ 金融服务 │
│ 2014-01-01 00:00:00 ┆ 2021-07-30 00:00:00 ┆ 000001 ┆ 3        ┆ 银行     │
│ 2021-07-30 00:00:00 ┆ null                ┆ 000001 ┆ 3        ┆ 银行     │
│ 1991-01-29 00:00:00 ┆ 2021-07-30 00:00:00 ┆ 000002 ┆ 6        ┆ 房地产   │
│ 2021-07-30 00:00:00 ┆ null                ┆ 000002 ┆ 6        ┆ 房地产   │
│ …                   ┆ …                   ┆ …      ┆ …        ┆ …        │
│ 2026-05-29 00:00:00 ┆ null                ┆ X26031 ┆ 19402327 ┆ 纺织服饰 │
│ 2026-05-29 00:00:00 ┆ null                ┆ X26032 ┆ 623937   ┆ 电子     │
│ 2026-06-02 00:00:00 ┆ null                ┆ X26033 ┆ 629047   ┆ 交通运输 │
│ 2026-06-05 00:00:00 ┆ null                ┆ X26037 ┆ 23581318 ┆ 社会服务 │
│ 2026-06-05 00:00:00 ┆ null                ┆ X26038 ┆ 20485151 ┆ 机械设备 │
└─────────────────────┴─────────────────────┴────────┴──────────┴──────────┘

In [53]:
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)
dts = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)

df_dates = pl.DataFrame({"date": dts}).sort("date")
df_ticks = pl.DataFrame({"tick": ticks}).sort("tick")
df_base = df_dates.join(df_ticks, how="cross")

In [54]:
ind_processed = (
    ind
    .filter(pl.col("tick").is_in(ticks))
    .with_columns([
        pl.col("start_date").cast(pl.Datetime),
        pl.col("end_date").cast(pl.Datetime).fill_null(pl.datetime(2099, 12, 31))
    ])
    .sort(["tick", "start_date"])
)
ind_processed = (
    df_base
    .join_asof(
        ind_processed,
        left_on="date",
        right_on="start_date",
        by="tick",
        strategy="backward"
    )
    .filter(pl.col("date") < pl.col("end_date"))
    .select(["date", "tick", "industry"])
)
ind_processed

shape: (14_441_926, 3)
┌─────────────────────┬────────┬──────────┐
│ date                ┆ tick   ┆ industry │
│ ---                 ┆ ---    ┆ ---      │
│ datetime[μs]        ┆ str    ┆ str      │
╞═════════════════════╪════════╪══════════╡
│ 2008-01-02 00:00:00 ┆ 000001 ┆ 金融服务 │
│ 2008-01-02 00:00:00 ┆ 000002 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000004 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000005 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000006 ┆ 房地产   │
│ …                   ┆ …      ┆ …        │
│ 2025-12-31 00:00:00 ┆ 688805 ┆ 医药生物 │
│ 2025-12-31 00:00:00 ┆ 688807 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688809 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688819 ┆ 电力设备 │
│ 2025-12-31 00:00:00 ┆ 688981 ┆ 电子     │
└─────────────────────┴────────┴──────────┘

In [55]:
update_map = {
    "黑色金属": "钢铁",
    "建筑建材": "建筑材料",
    "化工": "基础化工",
    "交运设备": "汽车",
    "信息服务": "传媒",
    "信息设备": "电子",
    "商业贸易": "商贸零售",
    "纺织服装": "纺织服饰",
    "休闲服务": "社会服务",
    "餐饮旅游": "社会服务",
    "电气设备": "电力设备",
}
ind_processed = ind_processed.with_columns(pl.col('industry').replace(update_map).alias("industry"))
ind_processed

shape: (14_441_926, 3)
┌─────────────────────┬────────┬──────────┐
│ date                ┆ tick   ┆ industry │
│ ---                 ┆ ---    ┆ ---      │
│ datetime[μs]        ┆ str    ┆ str      │
╞═════════════════════╪════════╪══════════╡
│ 2008-01-02 00:00:00 ┆ 000001 ┆ 金融服务 │
│ 2008-01-02 00:00:00 ┆ 000002 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000004 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000005 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000006 ┆ 房地产   │
│ …                   ┆ …      ┆ …        │
│ 2025-12-31 00:00:00 ┆ 688805 ┆ 医药生物 │
│ 2025-12-31 00:00:00 ┆ 688807 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688809 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688819 ┆ 电力设备 │
│ 2025-12-31 00:00:00 ┆ 688981 ┆ 电子     │
└─────────────────────┴────────┴──────────┘

In [56]:
bank_tick = ind_processed.filter(pl.col('industry')=='银行')['tick'].unique()
financial_tick = ind_processed.filter(pl.col('industry')=='非银金融')['tick'].unique()
coal_tick = ind_processed.filter(pl.col('industry')=='煤炭')['tick'].unique()
petrochemicals_tick = ind_processed.filter(pl.col('industry')=='石油石化')['tick'].unique()

ind_final = (
    ind_processed
    .with_columns([
        # 1. 处理"金融服务"的拆分
        pl.when(pl.col("industry") == "金融服务")
        .then(
            pl.when(pl.col("tick").is_in(bank_tick)).then(pl.lit("银行"))
            .when(pl.col("tick").is_in(financial_tick)).then(pl.lit("非银金融"))
            .otherwise(pl.lit("非银金融"))
        )
        # 2. 处理"采掘"的拆分
        .when(pl.col("industry") == "采掘")
        .then(
            pl.when(pl.col("tick").is_in(coal_tick)).then(pl.lit("煤炭"))
            .when(pl.col("tick").is_in(petrochemicals_tick)).then(pl.lit("石油石化"))
            .otherwise(pl.lit("煤炭"))
        )
        # 3. 其他行业保持不变
        .otherwise(pl.col("industry"))
        .alias("industry")
    ])
)
ind_final

shape: (14_441_926, 3)
┌─────────────────────┬────────┬──────────┐
│ date                ┆ tick   ┆ industry │
│ ---                 ┆ ---    ┆ ---      │
│ datetime[μs]        ┆ str    ┆ str      │
╞═════════════════════╪════════╪══════════╡
│ 2008-01-02 00:00:00 ┆ 000001 ┆ 银行     │
│ 2008-01-02 00:00:00 ┆ 000002 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000004 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000005 ┆ 房地产   │
│ 2008-01-02 00:00:00 ┆ 000006 ┆ 房地产   │
│ …                   ┆ …      ┆ …        │
│ 2025-12-31 00:00:00 ┆ 688805 ┆ 医药生物 │
│ 2025-12-31 00:00:00 ┆ 688807 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688809 ┆ 电子     │
│ 2025-12-31 00:00:00 ┆ 688819 ┆ 电力设备 │
│ 2025-12-31 00:00:00 ┆ 688981 ┆ 电子     │
└─────────────────────┴────────┴──────────┘

In [57]:
# 1.1 行业→行业值映射
industry_to_id = {
    "商贸零售": 0, "轻工制造": 1, "汽车": 2, "美容护理": 3, "房地产": 4,
    "国防军工": 5, "通信": 6, "煤炭": 7, "交通运输": 8, "公用事业": 9,
    "机械设备": 10, "电力设备": 11, "环保": 12, "食品饮料": 13, "计算机": 14,
    "纺织服饰": 15, "家用电器": 16, "医药生物": 17, "钢铁": 18, "社会服务": 19,
    "有色金属": 20, "非银金融": 21, "综合": 22, "建筑装饰": 23, "农林牧渔": 24,
    "银行": 25, "传媒": 26, "基础化工": 27, "建筑材料": 28, "石油石化": 29, "电子": 30
}

# 1.2 行业→板块映射
industry_to_sector = {
    "商贸零售": "消费", "轻工制造": "消费", "汽车": "制造", "美容护理": "消费", "房地产": "金融地产",
    "国防军工": "制造", "通信": "科技", "煤炭": "周期", "交通运输": "周期", "公用事业": "周期",
    "机械设备": "制造", "电力设备": "制造", "环保": "制造", "食品饮料": "消费", "计算机": "科技",
    "纺织服饰": "消费", "家用电器": "消费", "医药生物": "消费", "钢铁": "周期", "社会服务": "消费",
    "有色金属": "周期", "非银金融": "金融地产", "综合": "制造", "建筑装饰": "周期", "农林牧渔": "周期",
    "银行": "金融地产", "传媒": "科技", "基础化工": "周期", "建筑材料": "周期", "石油石化": "周期", "电子": "科技"
}

# 1.3 板块→板块ID映射
sector_to_id = {
    "消费": 0,
    "制造": 1,
    "金融地产": 2,
    "科技": 3,
    "周期": 4
}

In [58]:
ind_sector_id = (
    ind_final
    .with_columns([
        pl.col("industry").replace(industry_to_id).alias("industry_id"),
        pl.col("industry").replace(industry_to_sector).alias("sector")
    ])
    .with_columns([
        pl.col("sector").replace(sector_to_id).alias("sector_id")
    ])
)

df_industry = (
    ind_sector_id
    .pivot(index="date", columns="tick", values="industry_id")
    .sort("date")
    .with_columns([
        pl.all().exclude("date").cast(pl.Float64).fill_null(np.nan)
    ])
)

df_sector = (
    ind_sector_id
    .pivot(index="date", columns="tick", values="sector_id")
    .sort("date")
    .with_columns([
        pl.all().exclude("date").cast(pl.Float64).fill_null(np.nan)
    ])
)

In [60]:
df_industry.to_pandas().set_index('date').values.astype(float).tofile('/data/xujiayi/end2end/mask/industry.bin')

In [61]:
df_sector.to_pandas().set_index('date').values.astype(float).tofile('/data/xujiayi/end2end/mask/sector.bin')

#### IndCapGraph_Model

In [ ]:
sql1 = f'''
SELECT
    A.TradingDay            AS date,
    B.SecuCode              AS tick,
    A.PE                    AS pe,
    A.PB                    AS pb, 
    A.DebtToAssetValue1     AS debt_ratio                 
FROM (
    SELECT TradingDay, InnerCode, PE, PB, DebtToAssetValue1 FROM DZ_DIndicesForValuation
    UNION ALL
    SELECT TradingDay, InnerCode, PE, PB, DebtToAssetValue1 FROM LC_DIndicesForValuation
) A
LEFT JOIN SecuMain B 
ON A.InnerCode = B.InnerCode
WHERE B.SecuMarket IN (83, 90)
  AND B.SecuCategory = 1
  AND A.tradingday between '{start_dt}' and '{end_dt}'
ORDER BY date, tick
'''
df1 = pl.read_database(sql1, JY_CONN).unique()
df1

shape: (20_786_146, 5)
┌─────────────────────┬────────┬───────────────┬───────────────┬───────────────┐
│ date                ┆ tick   ┆ pe            ┆ pb            ┆ debt_ratio    │
│ ---                 ┆ ---    ┆ ---           ┆ ---           ┆ ---           │
│ datetime[μs]        ┆ str    ┆ decimal[38,4] ┆ decimal[38,4] ┆ decimal[38,4] │
╞═════════════════════╪════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2011-06-05 00:00:00 ┆ 002496 ┆ 41.1387       ┆ 1.9863        ┆ 0.0785        │
│ 2023-01-01 00:00:00 ┆ 300329 ┆ -16.1029      ┆ 1.8933        ┆ 0.2179        │
│ 2018-12-19 00:00:00 ┆ 601858 ┆ 17.3575       ┆ 2.1359        ┆ 0.1474        │
│ 2024-11-15 00:00:00 ┆ 600241 ┆ 60.8685       ┆ 1.8271        ┆ 0.0628        │
│ 2024-04-13 00:00:00 ┆ 300235 ┆ 70.7572       ┆ 3.1851        ┆ 0.0067        │
│ …                   ┆ …      ┆ …             ┆ …             ┆ …             │
│ 2017-08-11 00:00:00 ┆ 002140 ┆ 58.9409       ┆ 2.5801        ┆ 0.4238        │
│ 2018-12-29 00:00:00 ┆ 600750 ┆ 15.7849       ┆ 2.2690        ┆ 0.0571        │
│ 2023-03-01 00:00:00 ┆ 300107 ┆ 58.4180       ┆ 2.1853        ┆ 0.0348        │
│ 2011-01-26 00:00:00 ┆ 002146 ┆ 22.1808       ┆ 4.2827        ┆ 0.4186        │
│ 2015-08-04 00:00:00 ┆ 600538 ┆ -115.1320     ┆ 8.1143        ┆ 0.0436        │
└─────────────────────┴────────┴───────────────┴───────────────┴───────────────┘

In [ ]:
# 标记重复行（包含所有副本）
df1 = df1.with_columns(
    pl.struct(["date", "tick"]).is_duplicated().alias("is_dup")
)

# 查看所有重复行
dup_rows = df1.filter(pl.col("is_dup"))
print("🔥 重复行数量：", len(dup_rows))
print(dup_rows)

🔥 重复行数量： 0
shape: (0, 6)
┌──────────────┬──────┬───────────────┬───────────────┬───────────────┬────────┐
│ date         ┆ tick ┆ pe            ┆ pb            ┆ debt_ratio    ┆ is_dup │
│ ---          ┆ ---  ┆ ---           ┆ ---           ┆ ---           ┆ ---    │
│ datetime[μs] ┆ str  ┆ decimal[38,4] ┆ decimal[38,4] ┆ decimal[38,4] ┆ bool   │
╞══════════════╪══════╪═══════════════╪═══════════════╪═══════════════╪════════╡
└──────────────┴──────┴───────────────┴───────────────┴───────────────┴────────┘

In [ ]:
sql2 = f'''
SELECT
    C.EndDate                AS report_date,
    C.InfoPublDate           AS date,    
    B.SecuCode               AS tick,
    C.ROETTM                 AS roe,  
    C.OperatingRevenuePSTTM  AS revenue,     
    C.OperCashFlowPSTTM      AS ocf                    
FROM (
    SELECT EndDate, InfoPublDate, CompanyCode, ROETTM, OperatingRevenuePSTTM, OperCashFlowPSTTM FROM LC_MainIndexNew
    UNION ALL
    SELECT EndDate, InfoPublDate, CompanyCode, ROETTM, OperatingRevenuePSTTM, OperCashFlowPSTTM FROM LC_STIBMainIndex
) C 
LEFT JOIN SecuMain B 
ON B.CompanyCode = C.CompanyCode
WHERE B.SecuMarket IN (83, 90)
  AND B.SecuCategory = 1         
  AND C.InfoPublDate <= '{end_dt}'        
'''

df2 = pl.from_pandas(pd.read_sql(sql2, JY_CONN))

df2 = (
    df2
    .with_columns(
        pl.col("date").dt.cast_time_unit("us")          # 时间精度对齐 df1
    )
    # 关键：同一(tick, pub_date)只保留最新财报（end_date 最大）
    .sort(["tick", "date", "report_date"])
    .unique(subset=["tick", "date"], keep="last")  
    .select(["date", "tick", "roe", "revenue", "ocf"])
    .sort(["tick", "date"])
)
df2

shape: (283_091, 5)
┌─────────────────────┬────────┬──────────┬─────────┬────────┐
│ date                ┆ tick   ┆ roe      ┆ revenue ┆ ocf    │
│ ---                 ┆ ---    ┆ ---      ┆ ---     ┆ ---    │
│ datetime[μs]        ┆ str    ┆ f64      ┆ f64     ┆ f64    │
╞═════════════════════╪════════╪══════════╪═════════╪════════╡
│ 1992-03-08 00:00:00 ┆ 000001 ┆ 174.4708 ┆ 3.729   ┆ null   │
│ 1992-08-11 00:00:00 ┆ 000001 ┆ null     ┆ 2.4847  ┆ null   │
│ 1993-02-27 00:00:00 ┆ 000001 ┆ null     ┆ 3.5302  ┆ null   │
│ 1993-08-07 00:00:00 ┆ 000001 ┆ null     ┆ 1.9923  ┆ null   │
│ 1994-04-16 00:00:00 ┆ 000001 ┆ 22.6891  ┆ 2.9953  ┆ null   │
│ …                   ┆ …      ┆ …        ┆ …       ┆ …      │
│ 2023-12-31 00:00:00 ┆ X26016 ┆ 14.8796  ┆ 5.1438  ┆ 0.854  │
│ 2024-12-31 00:00:00 ┆ X26016 ┆ null     ┆ 5.9499  ┆ 1.9415 │
│ 2023-03-03 00:00:00 ┆ X26020 ┆ 25.7371  ┆ 5.647   ┆ 1.4444 │
│ 2024-12-27 00:00:00 ┆ X26020 ┆ 12.4565  ┆ 3.6617  ┆ 1.4125 │
│ 2025-06-30 00:00:00 ┆ X26020 ┆ 22.3343  ┆ 4.4047  ┆ 1.8213 │
└─────────────────────┴────────┴──────────┴─────────┴────────┘

df2 = df2.with_columns(
    pl.struct(["date", "tick"]).is_duplicated().alias("is_dup")
)
dup_rows = df2.filter(pl.col("is_dup"))
print("🔥 重复行数量：", len(dup_rows))
print(dup_rows)

In [ ]:
df2 = df2.with_columns(
    pl.col("date").dt.cast_time_unit("us")  # 转成和 df1 一样的微秒精度
)

all_dates = pl.concat([df1.select("date"), df2.select("date")]).unique()
all_ticks = pl.concat([df1.select("tick"), df2.select("tick")]).unique()
axis = all_dates.join(all_ticks, how="cross").unique()

df_full = axis.sort(['tick','date']).join(df1, on=["date", "tick"], how="left").join(df2, on=["date", "tick"], how="left")

fill_cols = ["roe", "revenue", "ocf"]  # 按你实际列名修改

df_final = (
    df_full
    .sort("tick", "date")  # 必须排序！ffill 依赖顺序
    .with_columns(
        pl.col(fill_cols).forward_fill().over("tick")
    )
)

ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True).tolist()
dts = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True).tolist()
df_final = df_final.filter(pl.col('date').is_in(dts)).filter(pl.col('tick').is_in(ticks)).unique().sort(['tick','date'])
df_final

shape: (23_787_936, 9)
┌───────────────┬────────┬───────────────┬───────────────┬───┬────────┬─────────┬─────────┬────────┐
│ date          ┆ tick   ┆ pe            ┆ pb            ┆ … ┆ is_dup ┆ roe     ┆ revenue ┆ ocf    │
│ ---           ┆ ---    ┆ ---           ┆ ---           ┆   ┆ ---    ┆ ---     ┆ ---     ┆ ---    │
│ datetime[μs]  ┆ str    ┆ decimal[38,4] ┆ decimal[38,4] ┆   ┆ bool   ┆ f64     ┆ f64     ┆ f64    │
╞═══════════════╪════════╪═══════════════╪═══════════════╪═══╪════════╪═════════╪═════════╪════════╡
│ 2008-01-02    ┆ 000001 ┆ 34.6663       ┆ 9.4762        ┆ … ┆ false  ┆ 27.6584 ┆ 4.7923  ┆ 12.381 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2008-01-03    ┆ 000001 ┆ 34.0913       ┆ 9.3191        ┆ … ┆ false  ┆ 27.6584 ┆ 4.7923  ┆ 12.381 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2008-01-04    ┆ 000001 ┆ 35.0223       ┆ 9.5736        ┆ … ┆ false  ┆ 27.6584 ┆ 4.7923  ┆ 12.381 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2008-01-07    ┆ 000001 ┆ 35.7525       ┆ 9.7732        ┆ … ┆ false  ┆ 27.6584 ┆ 4.7923  ┆ 12.381 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2008-01-08    ┆ 000001 ┆ 40.5168       ┆ 11.0755       ┆ … ┆ false  ┆ 27.6584 ┆ 4.7923  ┆ 12.381 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ …             ┆ …      ┆ …             ┆ …             ┆ … ┆ …      ┆ …       ┆ …       ┆ …      │
│ 2025-12-25    ┆ 688981 ┆ 204.6940      ┆ 6.5134        ┆ … ┆ false  ┆ 3.182   ┆ 8.1787  ┆ 2.8354 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2025-12-26    ┆ 688981 ┆ 203.0642      ┆ 6.4615        ┆ … ┆ false  ┆ 3.182   ┆ 8.1787  ┆ 2.8354 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2025-12-29    ┆ 688981 ┆ 203.7294      ┆ 6.4827        ┆ … ┆ false  ┆ 3.182   ┆ 8.1787  ┆ 2.8354 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2025-12-30    ┆ 688981 ┆ 208.3528      ┆ 6.6298        ┆ … ┆ false  ┆ 3.182   ┆ 8.1787  ┆ 2.8354 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
│ 2025-12-31    ┆ 688981 ┆ 204.2782      ┆ 6.5001        ┆ … ┆ false  ┆ 3.182   ┆ 8.1787  ┆ 2.8354 │
│ 00:00:00      ┆        ┆               ┆               ┆   ┆        ┆         ┆         ┆        │
└───────────────┴────────┴───────────────┴───────────────┴───┴────────┴─────────┴─────────┴────────┘

In [ ]:
fields = ['pe','pb','debt_ratio','roe','revenue','ocf']
for f in fields:
    feat = df_final.pivot(index='date',columns='tick',values=f).to_pandas().set_index('date')
    print(feat)
    feat.values.astype(float).tofile(f'/data/xujiayi/end2end/PINN-MTICG/IndCapGAT/{f}.bin')

             000001   000002     000004   000005    000006    000007  \
date
2008-01-02  34.6663  73.9513  8288.0565  91.5368   41.3162  -16.5125
2008-01-03  34.0913  72.1779  8511.1964  94.9694   41.0375  -17.3221
2008-01-04  35.0223  74.0780  8622.7664  93.8252   43.0344  -17.3008
2008-01-07  35.7525  76.4595  8909.6607  96.4950   44.7992  -18.1744
2008-01-08  40.5168  75.6994  8758.2443  93.9523   43.5298  -18.1105
...             ...      ...        ...      ...       ...       ...
2025-12-25   5.2028  -0.9597   -11.7720     None  -12.9375   70.6793
2025-12-26   5.1938  -0.9556   -11.7396     None  -13.0786   69.6399
2025-12-29   5.2028  -0.9496   -11.7289     None  -12.5781   69.4565
2025-12-30   5.1668  -0.9256   -12.1493     None  -12.6551   71.0462
2025-12-31   5.1352  -0.9316   -11.9445     None  -12.7706   69.9456

              000008    000009    000010     000011  ...   688796   688798  \
date                                                 ...
2008-01-02  877.3736   62.3026  134.4898  -186.1899  ...     None     None
2008-01-03  875.2730   61.3663  134.4898  -190.2095  ...     None     None
2008-01-04  919.3867   61.4053  134.4898  -190.7837  ...     None     None
2008-01-07  902.5815   60.0009  134.4898  -190.0659  ...     None     None
2008-01-08  880.1745   58.1283  134.4898  -181.1655  ...     None     None
...              ...       ...       ...        ...  ...      ...      ...
2025-12-25  -17.4020  370.3503   92.4342    -4.9714  ...  92.6199  50.2819
2025-12-26  -17.4020  371.8141   90.6518    -4.9604  ...  91.0285  49.9712
2025-12-29  -17.2820  364.8609   91.1610    -4.9001  ...  92.7093  49.9712
2025-12-30  -17.1019  364.1290   89.3786    -4.8617  ...  91.6901  50.0175
2025-12-31  -17.1019  360.4694   89.8878    -4.9440  ...  94.0503  50.3083

             688799   688800     688802    688805    688807   688809   688819  \
date
2008-01-02     None     None       None      None      None     None     None
2008-01-03     None     None       None      None      None     None     None
2008-01-04     None     None       None      None      None     None     None
2008-01-07     None     None       None      None      None     None     None
2008-01-08     None     None       None      None      None     None     None
...             ...      ...        ...       ...       ...      ...      ...
2025-12-25  30.2053  59.8916  -264.4322  129.4902  195.8400     None  22.5035
2025-12-26  29.5395  58.8370  -254.8739  123.5148  178.7594     None  22.7985
2025-12-29  29.5333  61.2659  -252.9820  114.5518  176.2289     None  22.4432
2025-12-30  29.4224  58.7894  -250.4403  104.6900  171.4933  83.2355  22.4432
2025-12-31  29.4039  56.4694  -238.5870  102.3582  169.2701  94.5749  22.2689

              688981
date
2008-01-02      None
2008-01-03      None
2008-01-04      None
2008-01-07      None
2008-01-08      None
...              ...
2025-12-25  204.6940
2025-12-26  203.0642
2025-12-29  203.7294
2025-12-30  208.3528
2025-12-31  204.2782

[4376 rows x 5436 columns]
             000001  000002   000004  000005  000006    000007   000008  \
date
2008-01-02   9.4762  7.6842  11.9265  8.2359  4.9783  -27.1258  11.9093
2008-01-03   9.3191  7.4999  12.2476  8.5448  4.9447  -28.4558  11.8808
2008-01-04   9.5736  7.6973  12.4081  8.4418  5.1854  -28.4208  12.4796
2008-01-07   9.7732  7.9448  12.8209  8.6820  5.3980  -29.8559  12.2515
2008-01-08  11.0755  7.8658  12.6031  8.4532  5.2450  -29.7509  11.9473
...             ...     ...      ...     ...     ...       ...      ...
2025-12-25   0.5008  0.3252  39.1253    None  2.5215   21.9241   2.6875
2025-12-26   0.4999  0.3238  39.0178    None  2.5490   21.6017   2.6875
2025-12-29   0.5008  0.3218  38.9820    None  2.4515   21.5448   2.6689
2025-12-30   0.4973  0.3136  40.3793    None  2.4665   22.0379   2.6411
2025-12-31   0.4943  0.3157  39.6986    None  2.4890   21.6966   2.6411

            000009   000010   000011  ...   688796  688798  688799  688800  \
date                                  ...
2008-01-02  9.0008  30.3043  12.3023  ...     None    None    None    None
2008-01-03  8.8655  30.3043  12.5679  ...     None    None    None    None
2008-01-04  8.8712  30.3043  12.6058  ...     None    None    None    None
2008-01-07  8.6683  30.3043  12.5584  ...     None    None    None    None
2008-01-08  8.3977  30.3043  11.9703  ...     None    None    None    None
...            ...      ...      ...  ...      ...     ...     ...     ...
2025-12-25  2.5899  12.7826   1.5910  ...  23.7243  4.2530  3.2301  7.8952
2025-12-26  2.6002  12.5361   1.5875  ...  23.3167  4.2268  3.1589  7.7562
2025-12-29  2.5515  12.6065   1.5682  ...  23.7472  4.2268  3.1582  8.0763
2025-12-30  2.5464  12.3600   1.5559  ...  23.4862  4.2307  3.1463  7.7499
2025-12-31  2.5208  12.4304   1.5823  ...  24.0907  4.2553  3.1444  7.4441

             688802   688805   688807   688809  688819  688981
date
2008-01-02     None     None     None     None    None    None
2008-01-03     None     None     None     None    None    None
2008-01-04     None     None     None     None    None    None
2008-01-07     None     None     None     None    None    None
2008-01-08     None     None     None     None    None    None
...             ...      ...      ...      ...     ...     ...
2025-12-25  26.9485  17.7251  21.3434     None  1.9368  6.5134
2025-12-26  25.9744  16.9072  19.4819     None  1.9621  6.4615
2025-12-29  25.7816  15.6803  19.2061     None  1.9316  6.4827
2025-12-30  25.5226  14.3304  18.6900  21.2520  1.9316  6.6298
2025-12-31  24.3146  14.0112  18.4477  24.1472  1.9166  6.5001

[4376 rows x 5436 columns]
            000001  000002  000004  000005  000006  000007  000008  000009  \
date
2008-01-02  0.8074  0.2464  0.0863  0.1015  0.3363  0.3442  0.0064  0.2009
2008-01-03  0.8099  0.2509  0.0842  0.0982  0.3378  0.3334  0.0064  0.2033
2008-01-04  0.8058  0.2460  0.0832  0.0993  0.3273  0.3337  0.0061  0.2032
2008-01-07  0.8025  0.2402  0.0808  0.0968  0.3185  0.3228  0.0062  0.2070
2008-01-08  0.7819  0.2420  0.0820  0.0992  0.3247  0.3236  0.0063  0.2123
...            ...     ...     ...     ...     ...     ...     ...     ...
2025-12-25  0.9590  0.9360  0.1302    None  0.4490  0.0415  0.4360  0.5636
2025-12-26  0.9591  0.9362  0.1305    None  0.4463  0.0421  0.4360  0.5627
2025-12-29  0.9590  0.9366  0.1306    None  0.4560  0.0422  0.4377  0.5673
2025-12-30  0.9593  0.9381  0.1266    None  0.4545  0.0413  0.4403  0.5678
2025-12-31  0.9595  0.9377  0.1285    None  0.4522  0.0419  0.4403  0.5703

            000010  000011  ...  688796  688798  688799  688800  688802  \
date                        ...
2008-01-02  0.0593  0.1440  ...    None    None    None    None    None
2008-01-03  0.0593  0.1414  ...    None    None    None    None    None
2008-01-04  0.0593  0.1410  ...    None    None    None    None    None
2008-01-07  0.0593  0.1415  ...    None    None    None    None    None
2008-01-08  0.0593  0.1474  ...    None    None    None    None    None
...            ...     ...  ...     ...     ...     ...     ...     ...
2025-12-25  0.3601  0.6905  ...  0.0595  0.0570  0.1092  0.1160  0.0023
2025-12-26  0.3646  0.6910  ...  0.0605  0.0573  0.1114  0.1178  0.0024
2025-12-29  0.3633  0.6936  ...  0.0594  0.0573  0.1114  0.1137  0.0024
2025-12-30  0.3679  0.6953  ...  0.0601  0.0573  0.1118  0.1179  0.0025
2025-12-31  0.3665  0.6917  ...  0.0587  0.0570  0.1118  0.1222  0.0026

            688805  688807  688809  688819  688981
date
2008-01-02    None    None    None    None    None
2008-01-03    None    None    None    None    None
2008-01-04    None    None    None    None    None
2008-01-07    None    None    None    None    None
2008-01-08    None    None    None    None    None
...            ...     ...     ...     ...     ...
2025-12-25  0.0195  0.0037    None  0.4617  0.1056
2025-12-26  0.0205  0.0041    None  0.4585  0.1063
2025-12-29  0.0220  0.0042    None  0.4624  0.1060
2025-12-30  0.0240  0.0043  0.0087  0.4624  0.1039
2025-12-31  0.0246  0.0043  0.0076  0.4643  0.1058

[4376 rows x 5436 columns]
             000001   000002    000004   000005   000006   000007   000008  \
date
2008-01-02  27.6584  10.5781   -0.5388  -5.9869  12.2942 -10.6167   1.3574
2008-01-03  27.6584  10.5781   -0.5388  -5.9869  12.2942 -10.6167   1.3574
2008-01-04  27.6584  10.5781   -0.5388  -5.9869  12.2942 -10.6167   1.3574
2008-01-07  27.6584  10.5781   -0.5388  -5.9869  12.2942 -10.6167   1.3574
2008-01-08  27.6584  10.5781   -0.5388  -5.9869  12.2942 -10.6167   1.3574
...             ...      ...       ...      ...      ...      ...      ...
2025-12-25   8.3251 -33.8828 -332.3600 -14.5115 -19.4899  31.0192 -15.4435
2025-12-26   8.3251 -33.8828 -332.3600 -14.5115 -19.4899  31.0192 -15.4435
2025-12-29   8.3251 -33.8828 -332.3600 -14.5115 -19.4899  31.0192 -15.4435
2025-12-30   8.3251 -33.8828 -332.3600 -14.5115 -19.4899  31.0192 -15.4435
2025-12-31   8.3251 -33.8828 -332.3600 -14.5115 -19.4899  31.0192 -15.4435

             000009   000010   000011  ...   688796  688798   688799   688800  \
date                                   ...
2008-01-02  17.4587  18.4950  -7.1357  ...      NaN     NaN      NaN      NaN
2008-01-03  17.4587  18.4950  -7.1357  ...      NaN     NaN      NaN      NaN
2008-01-04  17.4587  18.4950  -7.1357  ...      NaN     NaN      NaN      NaN
2008-01-07  17.4587  18.4950  -7.1357  ...      NaN     NaN      NaN      NaN
2008-01-08  17.4587  18.4950  -7.1357  ...      NaN     NaN      NaN      NaN
...             ...      ...      ...  ...      ...     ...      ...      ...
2025-12-25   0.6993  13.8288 -32.0036  ...  25.6147  8.4584  10.6937  13.1825
2025-12-26   0.6993  13.8288 -32.0036  ...  25.6147  8.4584  10.6937  13.1825
2025-12-29   0.6993  13.8288 -32.0036  ...  25.6147  8.4584  10.6937  13.1825
2025-12-30   0.6993  13.8288 -32.0036  ...  25.6147  8.4584  10.6937  13.1825
2025-12-31   0.6993  13.8288 -32.0036  ...  25.6147  8.4584  10.6937  13.1825

             688802   688805   688807   688809  688819  688981
date
2008-01-02      NaN      NaN      NaN      NaN     NaN     NaN
2008-01-03      NaN      NaN      NaN      NaN     NaN     NaN
2008-01-04      NaN      NaN      NaN      NaN     NaN     NaN
2008-01-07      NaN      NaN      NaN      NaN     NaN     NaN
2008-01-08      NaN      NaN      NaN      NaN     NaN     NaN
...             ...      ...      ...      ...     ...     ...
2025-12-25 -10.1911  13.6884  10.8984  25.5323  8.6065   3.182
2025-12-26 -10.1911  13.6884  10.8984  25.5323  8.6065   3.182
2025-12-29 -10.1911  13.6884  10.8984  25.5323  8.6065   3.182
2025-12-30 -10.1911  13.6884  10.8984  25.5323  8.6065   3.182
2025-12-31 -10.1911  13.6884  10.8984  25.5323  8.6065   3.182

[4376 rows x 5436 columns]
            000001   000002  000004  000005  000006  000007  000008  000009  \
date
2008-01-02  4.7923   3.4318  0.6256  0.1973  2.3203  1.1260  0.1323  2.1654
2008-01-03  4.7923   3.4318  0.6256  0.1973  2.3203  1.1260  0.1323  2.1654
2008-01-04  4.7923   3.4318  0.6256  0.1973  2.3203  1.1260  0.1323  2.1654
2008-01-07  4.7923   3.4318  0.6256  0.1973  2.3203  1.1260  0.1323  2.1654
2008-01-08  4.7923   3.4318  0.6256  0.1973  2.3203  1.1260  0.1323  2.1654
...            ...      ...     ...     ...     ...     ...     ...     ...
2025-12-25  6.9969  23.8603  0.5574  0.2238  2.5495  1.3073  0.7837  8.6866
2025-12-26  6.9969  23.8603  0.5574  0.2238  2.5495  1.3073  0.7837  8.6866
2025-12-29  6.9969  23.8603  0.5574  0.2238  2.5495  1.3073  0.7837  8.6866
2025-12-30  6.9969  23.8603  0.5574  0.2238  2.5495  1.3073  0.7837  8.6866
2025-12-31  6.9969  23.8603  0.5574  0.2238  2.5495  1.3073  0.7837  8.6866

            000010  000011  ...  688796   688798   688799   688800  688802  \
date                        ...
2008-01-02  0.6041  0.6008  ...     NaN      NaN      NaN      NaN     NaN
2008-01-03  0.6041  0.6008  ...     NaN      NaN      NaN      NaN     NaN
2008-01-04  0.6041  0.6008  ...     NaN      NaN      NaN      NaN     NaN
2008-01-07  0.6041  0.6008  ...     NaN      NaN      NaN      NaN     NaN
2008-01-08  0.6041  0.6008  ...     NaN      NaN      NaN      NaN     NaN
...            ...     ...  ...     ...      ...      ...      ...     ...
2025-12-25  0.7942  5.2554  ...  3.3336  11.7671  10.8854  15.2983  4.8773
2025-12-26  0.7942  5.2554  ...  3.3336  11.7671  10.8854  15.2983  4.8773
2025-12-29  0.7942  5.2554  ...  3.3336  11.7671  10.8854  15.2983  4.8773
2025-12-30  0.7942  5.2554  ...  3.3336  11.7671  10.8854  15.2983  4.8773
2025-12-31  0.7942  5.2554  ...  3.3336  11.7671  10.8854  15.2983  4.8773

            688805  688807  688809   688819  688981
date
2008-01-02     NaN     NaN     NaN      NaN     NaN
2008-01-03     NaN     NaN     NaN      NaN     NaN
2008-01-04     NaN     NaN     NaN      NaN     NaN
2008-01-07     NaN     NaN     NaN      NaN     NaN
2008-01-08     NaN     NaN     NaN      NaN     NaN
...            ...     ...     ...      ...     ...
2025-12-25  4.2337  7.7652  9.2451  46.8638  8.1787
2025-12-26  4.2337  7.7652  9.2451  46.8638  8.1787
2025-12-29  4.2337  7.7652  9.2451  46.8638  8.1787
2025-12-30  4.2337  7.7652  9.2451  46.8638  8.1787
2025-12-31  4.2337  7.7652  9.2451  46.8638  8.1787

[4376 rows x 5436 columns]
             000001  000002  000004  000005  000006  000007  000008  000009  \
date
2008-01-02  12.3810 -0.6738 -0.0143  0.1049 -3.3927  0.2003  0.0382  0.0644
2008-01-03  12.3810 -0.6738 -0.0143  0.1049 -3.3927  0.2003  0.0382  0.0644
2008-01-04  12.3810 -0.6738 -0.0143  0.1049 -3.3927  0.2003  0.0382  0.0644
2008-01-07  12.3810 -0.6738 -0.0143  0.1049 -3.3927  0.2003  0.0382  0.0644
2008-01-08  12.3810 -0.6738 -0.0143  0.1049 -3.3927  0.2003  0.0382  0.0644
...             ...     ...     ...     ...     ...     ...     ...     ...
2025-12-25  -0.1051  0.2312 -0.0394 -0.0269  1.1172  1.3365  0.1648  0.5244
2025-12-26  -0.1051  0.2312 -0.0394 -0.0269  1.1172  1.3365  0.1648  0.5244
2025-12-29  -0.1051  0.2312 -0.0394 -0.0269  1.1172  1.3365  0.1648  0.5244
2025-12-30  -0.1051  0.2312 -0.0394 -0.0269  1.1172  1.3365  0.1648  0.5244
2025-12-31  -0.1051  0.2312 -0.0394 -0.0269  1.1172  1.3365  0.1648  0.5244

            000010  000011  ...  688796  688798  688799  688800  688802  \
date                        ...
2008-01-02  0.1002 -0.2020  ...     NaN     NaN     NaN     NaN     NaN
2008-01-03  0.1002 -0.2020  ...     NaN     NaN     NaN     NaN     NaN
2008-01-04  0.1002 -0.2020  ...     NaN     NaN     NaN     NaN     NaN
2008-01-07  0.1002 -0.2020  ...     NaN     NaN     NaN     NaN     NaN
2008-01-08  0.1002 -0.2020  ...     NaN     NaN     NaN     NaN     NaN
...            ...     ...  ...     ...     ...     ...     ...     ...
2025-12-25  0.0385 -3.4334  ...  0.9359  1.9041  2.1845 -0.4486 -4.2266
2025-12-26  0.0385 -3.4334  ...  0.9359  1.9041  2.1845 -0.4486 -4.2266
2025-12-29  0.0385 -3.4334  ...  0.9359  1.9041  2.1845 -0.4486 -4.2266
2025-12-30  0.0385 -3.4334  ...  0.9359  1.9041  2.1845 -0.4486 -4.2266
2025-12-31  0.0385 -3.4334  ...  0.9359  1.9041  2.1845 -0.4486 -4.2266

            688805  688807  688809  688819  688981
date
2008-01-02     NaN     NaN     NaN     NaN     NaN
2008-01-03     NaN     NaN     NaN     NaN     NaN
2008-01-04     NaN     NaN     NaN     NaN     NaN
2008-01-07     NaN     NaN     NaN     NaN     NaN
2008-01-08     NaN     NaN     NaN     NaN     NaN
...            ...     ...     ...     ...     ...
2025-12-25  0.4479  2.7177  3.9888    6.31  2.8354
2025-12-26  0.4479  2.7177  3.9888    6.31  2.8354
2025-12-29  0.4479  2.7177  3.9888    6.31  2.8354
2025-12-30  0.4479  2.7177  3.9888    6.31  2.8354
2025-12-31  0.4479  2.7177  3.9888    6.31  2.8354

[4376 rows x 5436 columns]

In [ ]:
revenue = np.memmap(f'/data/xujiayi/end2end/PINN-MTICG/IndCapGAT/revenue.bin', shape=(3400, 5422), dtype=float, mode="r")
revenue

lag_revenue = np.roll(revenue, 242, axis=0)
lag_revenue[:242] = np.nan
revenue_yoy = lag_revenue / revenue - 1
revenue_yoy

revenue_yoy.astype(float).tofile(f'/data/xujiayi/end2end/PINN-MTICG/IndCapGAT/revenue_yoy.bin')

#### Indices_Mask

In [ ]:
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)
dts = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)

In [ ]:
sql = f'''
select 
    B.SecuCode as 'index',
    C.SecuCode as 'tick',
    A.EndDate as 'date',
    A.Weight as 'weight'
from LC_IndexComponentsWeight A
left join SecuMain B on A.IndexCode=B.InnerCode
left join SecuMain C on A.InnerCode=C.InnerCode
where B.SecuCode in ('000300','000905','000510','000852','932000','000985')
'''
index_compt = pl.read_database(sql, JY_CONN)
index_compt

shape: (1_021_414, 4)
┌────────┬────────┬─────────────────────┬───────────────┐
│ index  ┆ tick   ┆ date                ┆ weight        │
│ ---    ┆ ---    ┆ ---                 ┆ ---           │
│ str    ┆ str    ┆ datetime[μs]        ┆ decimal[38,6] │
╞════════╪════════╪═════════════════════╪═══════════════╡
│ 000510 ┆ 000001 ┆ 2024-09-30 00:00:00 ┆ 0.524000      │
│ 000510 ┆ 000001 ┆ 2024-10-31 00:00:00 ┆ 0.496000      │
│ 000510 ┆ 000001 ┆ 2024-11-29 00:00:00 ┆ 0.495000      │
│ 000510 ┆ 000001 ┆ 2024-12-31 00:00:00 ┆ 0.502000      │
│ 000510 ┆ 000001 ┆ 2025-01-27 00:00:00 ┆ 0.507000      │
│ …      ┆ …      ┆ …                   ┆ …             │
│ 000985 ┆ 920026 ┆ 2025-12-31 00:00:00 ┆ 0.002000      │
│ 000985 ┆ 920026 ┆ 2026-01-30 00:00:00 ┆ 0.002000      │
│ 000985 ┆ 920026 ┆ 2026-02-27 00:00:00 ┆ 0.002000      │
│ 000985 ┆ 920026 ┆ 2026-03-31 00:00:00 ┆ 0.001000      │
│ 000985 ┆ 920026 ┆ 2026-04-30 00:00:00 ┆ 0.001000      │
└────────┴────────┴─────────────────────┴───────────────┘

In [ ]:
index_compt = index_compt.sort(['index','date','tick'])

hs300 = index_compt.filter(pl.col('index')=='000300').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(hs300.index))))
hs300 = hs300.reindex(index=dates)
hs300 = hs300.ffill().reindex(dts).replace(-999,np.nan)
hs300

zz500 = index_compt.filter(pl.col('index')=='000905').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(zz500.index))))
zz500 = zz500.reindex(index=dates)
zz500 = zz500.ffill().reindex(dts).replace(-999,np.nan)
zz500

a500 = index_compt.filter(pl.col('index')=='000510').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(a500.index))))
a500 = a500.reindex(index=dates)
a500 = a500.ffill().reindex(dts).replace(-999,np.nan)
a500

zz1000 = index_compt.filter(pl.col('index')=='000852').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(zz1000.index))))
zz1000 = zz1000.reindex(index=dates)
zz1000 = zz1000.ffill().reindex(dts).replace(-999,np.nan)
zz1000

zz2000 = index_compt.filter(pl.col('index')=='932000').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(zz2000.index))))
zz2000 = zz2000.reindex(index=dates)
zz2000 = zz2000.ffill().reindex(dts).replace(-999,np.nan)
zz2000

zzfull = index_compt.filter(pl.col('index')=='000985').pivot(index='date',columns='tick',values='weight').to_pandas().set_index('date').reindex(columns=ticks).fillna(-999)
dates = sorted(list(set(dts).union(set(zzfull.index))))
zzfull = zzfull.reindex(index=dates)
zzfull = zzfull.ffill().reindex(dts).replace(-999,np.nan)
zzfull

,000001,000002,000004,000005,000006,000007,000008,000009,000010,000011,...,688796,688798,688799,688800,688802,688805,688807,688809,688819,688981
date,,,,,,,,,,,,,,,,,,,,,
2008-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-25,0.219000,0.071000,NaN,NaN,0.020000,0.005000,0.012000,0.035000,0.004000,0.004000,...,NaN,0.013000,0.006000,0.016000,NaN,NaN,NaN,NaN,0.008000,0.439000
2025-12-26,0.219000,0.071000,NaN,NaN,0.020000,0.005000,0.012000,0.035000,0.004000,0.004000,...,NaN,0.013000,0.006000,0.016000,NaN,NaN,NaN,NaN,0.008000,0.439000
2025-12-29,0.219000,0.071000,NaN,NaN,0.020000,0.005000,0.012000,0.035000,0.004000,0.004000,...,NaN,0.013000,0.006000,0.016000,NaN,NaN,NaN,NaN,0.008000,0.439000
2025-12-30,0.219000,0.071000,NaN,NaN,0.020000,0.005000,0.012000,0.035000,0.004000,0.004000,...,NaN,0.013000,0.006000,0.016000,NaN,NaN,NaN,NaN,0.008000,0.439000
2025-12-31,0.204000,0.058000,NaN,NaN,0.017000,0.005000,0.010000,0.033000,0.004000,0.004000,...,NaN,0.013000,0.006000,0.019000,NaN,NaN,NaN,NaN,0.008000,0.452000

In [ ]:
hs300.values.astype(float).tofile('/data/xujiayi/end2end/mask/hs300_weight.bin')
zz500.values.astype(float).tofile('/data/xujiayi/end2end/mask/zz500_weight.bin')
a500.values.astype(float).tofile('/data/xujiayi/end2end/mask/a500_weight.bin')
zz1000.values.astype(float).tofile('/data/xujiayi/end2end/mask/zz1000_weight.bin')
zz2000.values.astype(float).tofile('/data/xujiayi/end2end/mask/zz2000_weight.bin')
zzfull.values.astype(float).tofile('/data/xujiayi/end2end/mask/zzfull_weight.bin')

In [ ]:
hs300 = hs300.values.astype(float)
zz500 = zz500.values.astype(float)
a500 = a500.values.astype(float)
zz1000 = zz1000.values.astype(float)
zz2000 = zz2000.values.astype(float)
zzfull = zzfull.values.astype(float)

In [ ]:
hs300_mask = ~np.isnan(hs300)
hs300_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/hs300_mask.bin')
zz500_mask = ~np.isnan(zz500)
zz500_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/zz500_mask.bin')
a500_mask = ~np.isnan(a500)
a500_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/a500_mask.bin')
zz1000_mask = ~np.isnan(zz1000)
zz1000_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/zz1000_mask.bin')
zz2000_mask = ~np.isnan(zz2000)
zz2000_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/zz2000_mask.bin')
zzfull_mask = ~np.isnan(zzfull)
zzfull_mask.astype(bool).tofile('/data/xujiayi/end2end/mask/zzfull_mask.bin')

#### Patch logMV for Basics

In [ ]:
sql_mv = f'''select
                    C.SecuCode as "tick",
                    A.TradingDay as "date",
                    A.NegotiableMV as "mv"
                from QT_StockPerformance A
                left join SecuMain C
                on A.InnerCode = C.InnerCode
                where A.TradingDay between '{start_dt}' and '{end_dt}'
                    and C.SecuMarket in (83,90)
                    and C.SecuCategory=1
                union all
                select
                    C.SecuCode as "tick",
                    B.TradingDay as "date",
                    B.NegotiableMV as "mv"
                from LC_STIBPerformance B
                left join SecuMain C
                on B.InnerCode = C.InnerCode
                where B.TradingDay between '{start_dt}' and '{end_dt}'
                    and C.SecuMarket in (83,90)
                    and C.SecuCategory=1
             '''
mv = pl.read_database(sql_mv, JY_CONN).sort('tick','date')
mv = mv.pivot(index='date', columns='tick', values='mv').drop('date').to_numpy().astype(float)
mv

array([[5.88761322e+10, 1.71737203e+11, 6.79013462e+08, ...,
                   nan,            nan,            nan],
       [5.78995138e+10, 1.67618805e+11, 6.97294594e+08, ...,
                   nan,            nan,            nan],
       [5.94807054e+10, 1.72031375e+11, 7.06435160e+08, ...,
                   nan,            nan,            nan],
       ...,
       [2.24328744e+11, 4.60557342e+10, 1.37401092e+09, ...,
                   nan, 3.25459080e+10, 2.44946412e+11],
       [2.22776295e+11, 4.48897663e+10, 1.42326315e+09, ...,
        5.50402356e+09, 3.25459080e+10, 2.50505196e+11],
       [2.21417903e+11, 4.51812583e+10, 1.39926847e+09, ...,
        6.25385271e+09, 3.22931620e+10, 2.45606268e+11]],
      shape=(4376, 5436))

In [ ]:
mv.astype(float).tofile('/data/xujiayi/end2end/d_field/mv.bin')

In [ ]:
logmv = np.log(mv)
logmv

array([[24.79870162, 25.86923126, 20.33615151, ...,         nan,
                nan,         nan],
       [24.78197483, 25.84495822, 20.36271854, ...,         nan,
                nan,         nan],
       [24.80891782, 25.87094271, 20.37574198, ...,         nan,
                nan,         nan],
       ...,
       [26.13637842, 24.55311811, 21.04099998, ...,         nan,
        24.20591748, 26.2243053 ],
       [26.12943395, 24.52747568, 21.07621806, ..., 22.42874522,
        24.20591748, 26.2467455 ],
       [26.12331772, 24.5339482 , 21.05921542, ..., 22.55646354,
        24.19812134, 26.22699555]], shape=(4376, 5436))

In [ ]:
logmv.astype(float).tofile('/data/xujiayi/end2end/d_field/logmv.bin')

In [ ]:
close = np.memmap('/data/xujiayi/end2end/d_field/close.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
nan_mask = np.isnan(close)
nan_mask

array([[False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       ...,
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]],
      shape=(4376, 5436))