In [1]:
import os
import sys

# 将项目根目录加入 sys.path（根据实际情况修改路径）
project_root = os.path.abspath('..')   # 或 os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 然后绝对导入
from utils import Processor, Calculator

In [2]:
import os
import polars as pl
import numpy as np
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time
from sqlalchemy import create_engine
import pymssql
from typing import List, Dict

import warnings
warnings.filterwarnings('ignore')

In [3]:
T,N = 3400, 5422
start_dt = '2008-01-01'     
end_dt = '2025-12-31'

ROOT = '/data/xujiayi/end2end/'

JY_CONFIG = {
    "server": '10.10.0.102',
    "user": 'jydbReader',
    "password": 'jy@9043!Reader',
    "database": 'jydb',
    "charset": 'cp936'
}
JY_CONN = pymssql.connect(**JY_CONFIG)

STR_CONN = create_engine('mysql+pymysql://QuantReader:Quant%40Reader%21zsfund.com@10.10.6.101:9030/HighFrequency')

In [4]:
dates = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)

close = np.memmap('/data/xujiayi/end2end/d_field/close.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
nan_mask = np.isnan(close)

industry = np.memmap('/data/xujiayi/xjy/mask/industry.bin', shape=(len(dates),len(ticks)), mode='r', dtype=float)
logmv = np.memmap('/data/xujiayi/xjy/d_field/logmv.bin', shape=(len(dates),len(ticks)), mode='r', dtype=float)

#### 获取季度财报数据

In [5]:
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.EPS,
                A.ROE,
                A.EPSTTM,
                A.ROETTM,
                A.ROICTTM,
                A.GrossIncomeRatioTTM,
                A.NetProfitRatioTTM,
                A.PeriodCostsRateTTM,
                A.AdminiExpenseRateTTM,
                A.TotalAssetTRateTTM,
                A.ARTRate,
                A.InventoryTRate,
                A.DebtAssetsRatio,
                A.LongDebtRatio,
                A.NPParentCompanyCutYOY,
                A.TotalAssetGrowRate,
                A.NetOperateCashFlowYOY,
                A.NOCFToOperatingNITTM,
                A.SaleServiceCashToORTTM,
                A.OperCashInToAsset,
                A.FixAssetRatio,
                A.IntangibleAssetRatio,
                A.DividendPaidRatio,
                A.RetainedEarningRatio

            from LC_MainIndexNew A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.EPS,
                B.ROE,
                B.EPSTTM,
                B.ROETTM,
                B.ROICTTM,
                B.GrossIncomeRatioTTM,
                B.NetProfitRatioTTM,
                B.PeriodCostsRateTTM,
                B.AdminiExpenseRateTTM,
                B.TotalAssetTRateTTM,
                B.ARTRate,
                B.InventoryTRate,
                B.DebtAssetsRatio,
                B.LongDebtRatio,
                B.NPParentCompanyCutYOY,
                B.TotalAssetGrowRate,
                B.NetOperateCashFlowYOY,
                B.NOCFToOperatingNITTM,
                B.SaleServiceCashToORTTM,
                B.OperCashInToAsset,
                B.FixAssetRatio,
                B.IntangibleAssetRatio,
                B.DividendPaidRatio,
                B.RetainedEarningRatio

            from LC_STIBMainIndex B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.IfAdjusted=2
        '''

f = pd.read_sql(sql_f, JY_CONN)
f = pl.from_pandas(f)
f = f.sort(["tick", "report_date", "date"]).filter(pl.col('tick').is_in(ticks)).filter(pl.col('report_date')>=pl.datetime(2007,12,31))
f = f.unique(subset=["tick", "date"], keep="last").unique(subset=["tick", "report_date"], keep="first")

In [6]:
feat_cols = [
    'EPS','ROE',
    'EPSTTM','ROETTM', 'ROICTTM', 'GrossIncomeRatioTTM', 'NetProfitRatioTTM',
    'PeriodCostsRateTTM', 'AdminiExpenseRateTTM',
    'TotalAssetTRateTTM', 'ARTRate', 'InventoryTRate',
    'DebtAssetsRatio', 'LongDebtRatio', 
    'NPParentCompanyCutYOY', 'TotalAssetGrowRate', 'NetOperateCashFlowYOY',   # 已经包含的同比变化
    'NOCFToOperatingNITTM', 'SaleServiceCashToORTTM', 'OperCashInToAsset',
    'FixAssetRatio', 'IntangibleAssetRatio',
]
f = f.select(['tick', 'report_date', 'date'] + feat_cols)

calendar = pl.DataFrame({'trade_date':dates})
df = f.sort('date').join_asof(calendar, left_on='date', right_on='trade_date', strategy='forward').sort('tick','date')
df = df.sort(['tick', 'trade_date', 'date']).unique(subset=['tick', 'trade_date'], keep='last')

date2idx = {d:i for i,d in enumerate(dates)}
tick2idx = {t:i for i,t in enumerate(ticks)}

date_idx = np.array([date2idx.get(x, -1) for x in df["trade_date"].to_list()], dtype=np.int32)
tick_idx = np.array([tick2idx.get(x, -1) for x in df["tick"].to_list()], dtype=np.int32)

df = df.with_columns([
    pl.Series("date_idx", date_idx),
    pl.Series("tick_idx", tick_idx),
]).filter(
    pl.col('date_idx').is_not_null()
)
df

shape: (226_645, 28)
┌────────┬─────────────┬─────────────┬─────────┬───┬────────────┬────────────┬──────────┬──────────┐
│ tick   ┆ report_date ┆ date        ┆ EPS     ┆ … ┆ Intangible ┆ trade_date ┆ date_idx ┆ tick_idx │
│ ---    ┆ ---         ┆ ---         ┆ ---     ┆   ┆ AssetRatio ┆ ---        ┆ ---      ┆ ---      │
│ str    ┆ datetime[μs ┆ datetime[μs ┆ f64     ┆   ┆ ---        ┆ datetime[μ ┆ i32      ┆ i32      │
│        ┆ ]           ┆ ]           ┆         ┆   ┆ f64        ┆ s]         ┆          ┆          │
╞════════╪═════════════╪═════════════╪═════════╪═══╪════════════╪════════════╪══════════╪══════════╡
│ 000099 ┆ 2021-03-31  ┆ 2021-04-27  ┆ 0.0554  ┆ … ┆ 1.691614   ┆ 2021-04-27 ┆ 3239     ┆ 60       │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 002302 ┆ 2023-03-31  ┆ 2023-04-22  ┆ -0.0484 ┆ … ┆ 1.547257   ┆ 2023-04-24 ┆ 3722     ┆ 883      │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 002973 ┆ 2020-09-30  ┆ 2020-10-27  ┆ 0.717   ┆ … ┆ 27.107461  ┆ 2020-10-27 ┆ 3116     ┆ 1531     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 600715 ┆ 2017-06-30  ┆ 2017-08-29  ┆ 0.1889  ┆ … ┆ 0.792635   ┆ 2017-08-29 ┆ 2350     ┆ 3638     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 002209 ┆ 2017-06-30  ┆ 2017-08-25  ┆ -0.046  ┆ … ┆ 1.351722   ┆ 2017-08-25 ┆ 2348     ┆ 791      │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ …      ┆ …           ┆ …           ┆ …       ┆ … ┆ …          ┆ …          ┆ …        ┆ …        │
│ 603605 ┆ 2019-09-30  ┆ 2019-10-30  ┆ 1.1925  ┆ … ┆ 11.873468  ┆ 2019-10-30 ┆ 2876     ┆ 4501     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 300130 ┆ 2014-09-30  ┆ 2014-10-23  ┆ 0.3842  ┆ … ┆ 2.559514   ┆ 2014-10-23 ┆ 1652     ┆ 1725     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 002453 ┆ 2013-09-30  ┆ 2013-10-28  ┆ 0.1399  ┆ … ┆ 5.534184   ┆ 2013-10-28 ┆ 1410     ┆ 1034     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 600819 ┆ 2022-09-30  ┆ 2022-10-29  ┆ 0.031   ┆ … ┆ 5.148202   ┆ 2022-10-31 ┆ 3604     ┆ 3736     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
│ 600433 ┆ 2008-06-30  ┆ 2008-08-26  ┆ 0.0067  ┆ … ┆ 2.283214   ┆ 2008-08-26 ┆ 160      ┆ 3397     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆         ┆   ┆            ┆ 00:00:00   ┆          ┆          │
└────────┴─────────────┴─────────────┴─────────┴───┴────────────┴────────────┴──────────┴──────────┘

#### 计算yoy

In [7]:
delta_cols = [
    'EPSTTM',
    'ROETTM',
    'ROICTTM',
    'GrossIncomeRatioTTM',
    'NetProfitRatioTTM',
    'PeriodCostsRateTTM',
    'AdminiExpenseRateTTM',
    'TotalAssetTRateTTM',
    'ARTRate',
    'InventoryTRate',
    'DebtAssetsRatio',
    'LongDebtRatio',
    'NOCFToOperatingNITTM',
    'SaleServiceCashToORTTM',
    'OperCashInToAsset',
    'FixAssetRatio',
    'IntangibleAssetRatio',
]

df = df.with_columns(
    pl.col('report_date').dt.offset_by('-1y').alias('report_date_lyr')
).join(
    df, how='left', left_on=['tick','report_date_lyr'], right_on=['tick','report_date'], suffix='_lyr'
).with_columns([
    ((pl.col(c)/pl.col(c+'_lyr').replace(0,None))-1).alias(c+'_yoy')
    for c in delta_cols
]).drop(
    [c+'_lyr' for c in delta_cols]
)
df

shape: (226_645, 55)
┌────────┬────────────┬────────────┬─────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ date       ┆ EPS     ┆ … ┆ SaleServic ┆ OperCashIn ┆ FixAssetR ┆ Intangibl │
│ ---    ┆ e          ┆ ---        ┆ ---     ┆   ┆ eCashToORT ┆ ToAsset_yo ┆ atio_yoy  ┆ eAssetRat │
│ str    ┆ ---        ┆ datetime[μ ┆ f64     ┆   ┆ TM_yoy     ┆ y          ┆ ---       ┆ io_yoy    │
│        ┆ datetime[μ ┆ s]         ┆         ┆   ┆ ---        ┆ ---        ┆ f64       ┆ ---       │
│        ┆ s]         ┆            ┆         ┆   ┆ f64        ┆ f64        ┆           ┆ f64       │
╞════════╪════════════╪════════════╪═════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 000099 ┆ 2021-03-31 ┆ 2021-04-27 ┆ 0.0554  ┆ … ┆ -0.179851  ┆ 0.057964   ┆ null      ┆ 0.011865  │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 002302 ┆ 2023-03-31 ┆ 2023-04-22 ┆ -0.0484 ┆ … ┆ 0.122663   ┆ -0.306917  ┆ null      ┆ -0.019825 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 002973 ┆ 2020-09-30 ┆ 2020-10-27 ┆ 0.717   ┆ … ┆ -0.023675  ┆ 2.590661   ┆ null      ┆ -0.094176 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 600715 ┆ 2017-06-30 ┆ 2017-08-29 ┆ 0.1889  ┆ … ┆ -0.142343  ┆ -2.617906  ┆ -0.175007 ┆ -0.232131 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 002209 ┆ 2017-06-30 ┆ 2017-08-25 ┆ -0.046  ┆ … ┆ 0.034981   ┆ -1.248092  ┆ -0.101453 ┆ 0.167838  │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …       ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 603605 ┆ 2019-09-30 ┆ 2019-10-30 ┆ 1.1925  ┆ … ┆ -0.065826  ┆ -0.656821  ┆ null      ┆ -0.070314 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 300130 ┆ 2014-09-30 ┆ 2014-10-23 ┆ 0.3842  ┆ … ┆ -0.1313    ┆ 0.091586   ┆ 0.676271  ┆ -0.105931 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 002453 ┆ 2013-09-30 ┆ 2013-10-28 ┆ 0.1399  ┆ … ┆ 0.147837   ┆ -3.687416  ┆ -0.110334 ┆ -0.274347 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 600819 ┆ 2022-09-30 ┆ 2022-10-29 ┆ 0.031   ┆ … ┆ 0.011522   ┆ -0.607492  ┆ null      ┆ 0.000196  │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
│ 600433 ┆ 2008-06-30 ┆ 2008-08-26 ┆ 0.0067  ┆ … ┆ null       ┆ null       ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆         ┆   ┆            ┆            ┆           ┆           │
└────────┴────────────┴────────────┴─────────┴───┴────────────┴────────────┴───────────┴───────────┘

#### 计算qoq

In [8]:
df = df.sort(
    ['tick','report_date']
).with_columns([
    pl.col(c).shift(1).over('tick').alias(c+'_lst')
    for c in delta_cols
]).with_columns([
    ((pl.col(c)/pl.col(c+'_lst').replace(0,None))-1).alias(c+'_qoq')
    for c in delta_cols
]).drop(
    [c+'_lst' for c in delta_cols]
)

#### 计算sue

In [9]:
sql_ff = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.OperatingRevenue/10000 as "or",
                A.OperatingProfit/10000 as "op",
                A.TotalProfit/10000 as "tp",
                A.NetProfit/10000 as "np"

            from LC_IncomeStatementAll A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and A.IfMerged=1
                and A.IfAdjusted=2
                and A.BulletinType=20

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.OperatingRevenue/10000 as "or",
                B.OperatingProfit/10000 as "op",
                B.TotalProfit/10000 as "tp",
                B.NetProfit/10000 as "np"
            from LC_STIBIncomeState B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.IfAdjusted=2
        '''

ff = pd.read_sql(sql_ff, JY_CONN)
ff = pl.from_pandas(ff)
ff = ff.sort(["tick", "report_date", "date"]).filter(pl.col('tick').is_in(ticks)).filter(pl.col('report_date')>=pl.datetime(2007,12,31))
ff = ff.unique(subset=["tick", "date"], keep="last").unique(subset=["tick", "report_date"], keep="first")

In [10]:
dff = df.join(
    ff, how='left', on=['tick','report_date']
).drop('date_right')
dff

shape: (226_645, 76)
┌────────┬───────────────┬──────────────┬────────┬───┬────────────┬──────────┬──────────┬──────────┐
│ tick   ┆ report_date   ┆ date         ┆ EPS    ┆ … ┆ or         ┆ op       ┆ tp       ┆ np       │
│ ---    ┆ ---           ┆ ---          ┆ ---    ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ datetime[μs]  ┆ datetime[μs] ┆ f64    ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪══════════════╪════════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ 000001 ┆ 2007-12-31    ┆ 2008-03-20   ┆ 1.1554 ┆ … ┆ 1080750.2  ┆ 372194.2 ┆ 377177.5 ┆ 264990.3 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-03-31    ┆ 2008-04-24   ┆ 0.4379 ┆ … ┆ 355327.0   ┆ 137635.1 ┆ 137910.5 ┆ 100418.2 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-06-30    ┆ 2008-08-21   ┆ 0.8975 ┆ … ┆ 711525.3   ┆ 284099.6 ┆ 282566.8 ┆ 214383.4 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-09-30    ┆ 2008-10-24   ┆ 1.3886 ┆ … ┆ 1074140.6  ┆ 436420.4 ┆ 431466.9 ┆ 331699.4 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-12-31    ┆ 2009-03-20   ┆ 0.1977 ┆ … ┆ 1451311.9  ┆ 80342.6  ┆ 79260.9  ┆ 61403.5  │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ …      ┆ …             ┆ …            ┆ …      ┆ … ┆ …          ┆ …        ┆ …        ┆ …        │
│ 688981 ┆ 2024-09-30    ┆ 2024-11-08   ┆ 0.3395 ┆ … ┆ 4.187872e6 ┆ 355244.5 ┆ 355369.2 ┆ 323266.0 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2024-12-31    ┆ 2025-03-28   ┆ 0.4637 ┆ … ┆ 5.779557e6 ┆ 629864.7 ┆ 629202.2 ┆ 537311.8 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-03-31    ┆ 2025-05-09   ┆ 0.1699 ┆ … ┆ 1630108.5  ┆ 247946.9 ┆ 248217.9 ┆ 232091.5 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-06-30    ┆ 2025-08-29   ┆ 0.2881 ┆ … ┆ 3234804.9  ┆ 363656.9 ┆ 362659.3 ┆ 336767.8 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-09-30    ┆ 2025-11-14   ┆ 0.4773 ┆ … ┆ 4951041.6  ┆ 618976.0 ┆ 618323.1 ┆ 577035.9 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
└────────┴───────────────┴──────────────┴────────┴───┴────────────┴──────────┴──────────┴──────────┘

In [11]:
from sqlalchemy.engine import URL

zyyx_url = URL.create(drivername="mssql+pymssql",
             username="zyyxReader",
             password="zyyx!5893@Fund",
             host="10.110.0.106",
             database="zyyx",)
             #query={"charset": "gb18030"})
# 如果需要在连接时指定 tds_version，可以这样处理
zyyx_engine = create_engine(
    zyyx_url,
    connect_args={
        "tds_version": "7.0",
        #"charset": "gb18030"
    }
)

zyyx_conn = zyyx_engine.connect()

In [12]:
con_sql = f"""
select 
    create_date as "con_infodate", 
    stock_code as "tick", 
    report_year,
    report_quarter,
    author_name,
    forecast_or,
    forecast_op,
    forecast_np,
    forecast_tp,
    forecast_roe,
    forecast_eps
from rpt_forecast_stk
where create_date <='{end_dt}'
"""
raw_con = pl.read_database(con_sql, zyyx_conn).sort(['tick','con_infodate'])

# 删除全null行
con = raw_con.filter(pl.col('report_year').is_not_null() & pl.col('report_quarter').is_not_null())

# 生成预测的报告日期
con = con.with_columns(
    pl.col("report_quarter").mul(3).alias("month"),
).with_columns(
    (pl.date(pl.col("report_year"), pl.col("month"), 1)
     .dt.offset_by("1mo")
     .dt.offset_by("-1d")
    ).alias("report_date")
).with_columns(
    pl.col("report_date").dt.to_string("%Y-%m-%d").alias("report_date")
).drop(['report_year','report_quarter','month'])

con = con.sort(['tick','report_date']).with_columns([
    pl.col('con_infodate').str.to_datetime(),
    pl.col('report_date').str.to_datetime(),
])

# 处理单独分析师一行, 然后按报告期去重取最新预测
con = (
    con.with_columns(
        pl.col("author_name")
        .str.replace_all(r"[、，]", ",")
        .str.split(",")
        .alias("author_list")
    )
    .explode("author_list")
    .drop("author_name")              # 删除旧列
    .rename({"author_list": "author_name"})  # 重命名
)
con = con.with_columns(
    pl.col("author_name").cast(pl.Categorical).to_physical().alias("author_id")
).drop('author_name')

con = (
    con
    .sort(by=["report_date", "author_id", "con_infodate"], descending=[False, False, True])
    .group_by(["report_date", "author_id"])
    .first()
)

# 生成上一报告期
con = con.join(
    dff.select(['tick','report_date','date']).sort(['tick','date']).with_columns(pl.col('date').shift(1).alias('date_lst')),
    how='left', on=['tick','report_date']
)

# 确保分析师预期发布，在两个发布日之间
con = con.filter( 
    (pl.col('con_infodate')>pl.col('date_lst')) & (pl.col('con_infodate')<pl.col('date'))
)
con

shape: (26_990, 12)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ report_dat ┆ author_id ┆ con_infoda ┆ tick   ┆ … ┆ forecast_ ┆ forecast_ ┆ date      ┆ date_lst  │
│ e          ┆ ---       ┆ te         ┆ ---    ┆   ┆ roe       ┆ eps       ┆ ---       ┆ ---       │
│ ---        ┆ u32       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ datetime[ │
│ datetime[μ ┆           ┆ datetime[μ ┆        ┆   ┆ f64       ┆ f64       ┆ μs]       ┆ μs]       │
│ s]         ┆           ┆ s]         ┆        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2016-12-31 ┆ 6761      ┆ 2017-03-30 ┆ 600867 ┆ … ┆ 21.39     ┆ 0.442     ┆ 2017-04-1 ┆ 2016-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 2         ┆ 6         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2016-12-31 ┆ 2358      ┆ 2017-04-11 ┆ 600867 ┆ … ┆ 16.3      ┆ 0.45      ┆ 2017-04-1 ┆ 2016-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 2         ┆ 6         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2020-06-30 ┆ 6860      ┆ 2020-05-13 ┆ 002013 ┆ … ┆ null      ┆ 0.09      ┆ 2020-08-2 ┆ 2020-04-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 6         ┆ 7         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2023-12-31 ┆ 8125      ┆ 2024-03-15 ┆ 000960 ┆ … ┆ 8.17      ┆ 0.91      ┆ 2024-04-1 ┆ 2023-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 2         ┆ 7         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2009-12-31 ┆ 1053      ┆ 2010-03-09 ┆ 001696 ┆ … ┆ 0.244     ┆ 0.63      ┆ 2010-03-1 ┆ 2009-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 9         ┆ 4         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ …          ┆ …         ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2021-12-31 ┆ 8364      ┆ 2021-10-30 ┆ 000792 ┆ … ┆ 58.0      ┆ 1.048     ┆ 2022-04-2 ┆ 2021-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 6         ┆ 8         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2021-12-31 ┆ 1444      ┆ 2022-04-18 ┆ 688223 ┆ … ┆ 8.6       ┆ 0.11      ┆ 2022-04-2 ┆ 2021-12-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 3         ┆ 8         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2021-12-31 ┆ 2941      ┆ 2021-11-12 ┆ 601766 ┆ … ┆ 7.9       ┆ 0.4       ┆ 2022-03-3 ┆ 2021-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 1         ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2024-12-31 ┆ 6484      ┆ 2025-02-27 ┆ 600988 ┆ … ┆ 22.7      ┆ 1.07      ┆ 2025-03-2 ┆ 2024-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 9         ┆ 1         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2021-12-31 ┆ 6401      ┆ 2022-03-14 ┆ 601607 ┆ … ┆ 11.9      ┆ 2.03      ┆ 2022-03-3 ┆ 2021-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 0         ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
sue_cols = [
    'forecast_or',
    'forecast_op',
    'forecast_np',
    'forecast_tp',
    'forecast_roe',
    'forecast_eps'
]

con_res = (
    con
    .with_columns([
        pl.col(c).median().over(['tick','report_date']).alias(c)
        for c in sue_cols
    ])
    .drop("author_id")   # 如果你的列名是 authorid / author_id，就改成实际列名
    .unique(
        subset=['tick','report_date'],
        keep="first",
        maintain_order=True,
    )
).drop(['con_infodate','date_lst']).sort(['tick','report_date'])

In [14]:
dff = dff.rename({'ROE':'roe', 'EPS':'eps'})
dff = dff.join(
    con_res, how='left', on=['tick','report_date']
)

In [21]:
sue_base_cols = ['or','op','tp','np','roe','eps']
final = dff.with_columns([
    (pl.col(c)-pl.col('forecast_'+c)).alias(c+'_ue')
    for c in sue_base_cols
]).sort(['tick','report_date']).with_columns([
    pl.col(c).shift(1).rolling_std(window_size=12, min_periods=1, ddof=0).over('tick').alias(f'{c}_uestd')
    for c in sue_base_cols
]).with_columns([
    (pl.col(c+'_ue') / pl.col(c+'_uestd').replace(0, None)).alias(c+'_sue')
    for c in sue_base_cols
])

In [22]:
feat_cols = [
    'NPParentCompanyCutYOY','TotalAssetGrowRate','NetOperateCashFlowYOY'
]+[
    c+'_yoy' for c in delta_cols
]+[
    c+'_qoq' for c in delta_cols
]+[
    c+'_sue' for c in sue_base_cols
]
idx_cols = ['tick','report_date','trade_date','tick_idx','date_idx']

final = final.select(idx_cols+feat_cols)
final

shape: (226_645, 48)
┌────────┬──────────────┬──────────────┬──────────┬───┬──────────┬──────────┬───────────┬──────────┐
│ tick   ┆ report_date  ┆ trade_date   ┆ tick_idx ┆ … ┆ tp_sue   ┆ np_sue   ┆ roe_sue   ┆ eps_sue  │
│ ---    ┆ ---          ┆ ---          ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ str    ┆ datetime[μs] ┆ datetime[μs] ┆ i32      ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
╞════════╪══════════════╪══════════════╪══════════╪═══╪══════════╪══════════╪═══════════╪══════════╡
│ 000001 ┆ 2007-12-31   ┆ 2008-03-20   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-03-31   ┆ 2008-04-24   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-06-30   ┆ 2008-08-21   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-09-30   ┆ 2008-10-24   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-12-31   ┆ 2009-03-20   ┆ 0        ┆ … ┆ -0.18354 ┆ 0.016603 ┆ -0.003922 ┆ 0.012726 │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ …      ┆ …            ┆ …            ┆ …        ┆ … ┆ …        ┆ …        ┆ …         ┆ …        │
│ 688981 ┆ 2024-09-30   ┆ 2024-11-08   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2024-12-31   ┆ 2025-03-28   ┆ 5435     ┆ … ┆ 0.026047 ┆ 0.387388 ┆ -0.099344 ┆ 0.007929 │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-03-31   ┆ 2025-05-09   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-06-30   ┆ 2025-08-29   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-09-30   ┆ 2025-11-14   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
└────────┴──────────────┴──────────────┴──────────┴───┴──────────┴──────────┴───────────┴──────────┘

#### 数据处理

In [24]:
ind = industry[final["date_idx"].to_numpy(), final["tick_idx"].to_numpy()]
final = final.with_columns(pl.Series("industry", ind))

logmv_vals = logmv[final["date_idx"].to_numpy(), final["tick_idx"].to_numpy()]
final = final.with_columns(pl.Series("logmv", logmv_vals))

for feat in feat_cols:
    # 行业中位数填补缺失
    industry_med = pl.col(feat).median().over(["trade_date", "industry"])
    final = final.with_columns(
        pl.when(pl.col(feat).is_null() & pl.col("industry").is_not_null())
        .then(industry_med)
        .otherwise(pl.col(feat))
        .alias(feat)
    )

    # 当日横截面 MAD 去极值
    market_med = pl.col(feat).median().over("trade_date")
    mad = (pl.col(feat) - market_med).abs().median().over("trade_date")
    upper = market_med + 3 * 1.4826 * mad
    lower = market_med - 3 * 1.4826 * mad
    final = final.with_columns(
        pl.when(pl.col(feat) > upper)
        .then(upper)
        .when(pl.col(feat) < lower)
        .then(lower)
        .otherwise(pl.col(feat))
        .alias(feat)
    )
    
    # 行业市值中性化
    mean_feat = pl.col(feat).mean().over(["trade_date", "industry"])
    mean_logmv = pl.col("logmv").mean().over(["trade_date", "industry"])
    cov = ((pl.col(feat) - mean_feat) * (pl.col("logmv") - mean_logmv)).mean().over(["trade_date", "industry"])
    var_logmv = ((pl.col("logmv") - mean_logmv) ** 2).mean().over(["trade_date", "industry"])
    beta = pl.when(var_logmv > 1e-12).then(cov / var_logmv).otherwise(0.0)
    residual = pl.col(feat) - mean_feat - beta * (pl.col("logmv") - mean_logmv)
    final = final.with_columns(residual.alias(feat))

    # 当日横截面标准化
    mean = pl.col(feat).mean().over("trade_date")
    std = pl.col(feat).std().over("trade_date")
    final = final.with_columns(
        pl.when((std == 0) | std.is_null())
        .then(0.0)
        .otherwise((pl.col(feat) - mean) / std)
        .alias(feat)
    )

In [25]:
from pathlib import Path
OUT = Path("/data/xujiayi/xjy/research_factors/model_input/ered_v2/")
OUT.mkdir(parents=True, exist_ok=True)

event_df = final.select(["tick_idx", "date_idx"] + feat_cols).sort(["tick_idx", "date_idx"])

event_x = event_df.select(feat_cols).to_numpy().astype(float)
event_x.tofile(OUT/"event_x.bin")
event_tick = event_df["tick_idx"].to_numpy().astype(np.int64)
event_tick.tofile(OUT/"event_tick.bin")
event_effective_idx = event_df["date_idx"].to_numpy().astype(np.int64)
event_effective_idx.tofile(OUT/"event_effective_idx.bin")

print(f"saved to: {OUT}")
print(f"event_x: {event_x.shape}")
print(f"event_tick: {event_tick.shape}")
print(f"event_effective_idx: {event_effective_idx.shape}")
print("event_x = 财报长表特征值")
print("event_tick = tick_idx")
print("event_effective_idx = date_idx")

saved to: /data/xujiayi/xjy/research_factors/model_input/ered_v2
event_x: (226645, 43)
event_tick: (226645,)
event_effective_idx: (226645,)
event_x = 财报长表特征值
event_tick = tick_idx
event_effective_idx = date_idx

In [29]:
for feat_name in feat_cols:
    feat = final.select(['tick','trade_date',feat_name]).sort(['tick','trade_date'])
    feat = feat.pivot(index='trade_date', columns='tick', values=feat_name)
    feat = feat.to_pandas().set_index('trade_date').reindex(index=dates).reindex(columns=ticks)
    feat.to_numpy().astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_input/ered_v2/raw/{feat_name}.bin')
    
    feat_fill = feat.ffill()
    feat_fill[nan_mask] = np.nan
    feat_fill = feat_fill.ffill()
    feat_fill.to_numpy().astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_input/ered_v2/ffill/{feat_name}.bin')