In [18]:
import os
import sys

# 将项目根目录加入 sys.path（根据实际情况修改路径）
project_root = os.path.abspath('..')   # 或 os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 然后绝对导入
from utils import Processor, Calculator

In [19]:
import os
import polars as pl
import numpy as np
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time
from sqlalchemy import create_engine
import pymssql
from typing import List, Dict

import warnings
warnings.filterwarnings('ignore')

In [20]:
T,N = 3400, 5422
start_dt = '2008-01-01'     
end_dt = '2025-12-31'

ROOT = '/data/xujiayi/end2end/'

JY_CONFIG = {
    "server": '10.10.0.102',
    "user": 'jydbReader',
    "password": 'jy@9043!Reader',
    "database": 'jydb',
    "charset": 'cp936'
}
JY_CONN = pymssql.connect(**JY_CONFIG)

STR_CONN = create_engine('mysql+pymysql://QuantReader:Quant%40Reader%21zsfund.com@10.10.6.101:9030/HighFrequency')

In [21]:
dates = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)

close = np.memmap('/data/xujiayi/end2end/d_field/close.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
nan_mask = np.isnan(close)

industry = np.memmap('/data/xujiayi/xjy/mask/industry.bin', shape=(len(dates),len(ticks)), mode='r', dtype=float)
logmv = np.memmap('/data/xujiayi/xjy/d_field/logmv.bin', shape=(len(dates),len(ticks)), mode='r', dtype=float)

#### 获取季度财报数据

In [22]:
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.EPS,
                A.ROE,
                A.EPSTTM,
                A.ROETTM,
                A.ROICTTM,
                A.GrossIncomeRatioTTM,
                A.NetProfitRatioTTM,
                A.PeriodCostsRateTTM,
                A.AdminiExpenseRateTTM,
                A.TotalAssetTRateTTM,
                A.ARTRate,
                A.InventoryTRate,
                A.DebtAssetsRatio,
                A.LongDebtRatio,
                A.NPParentCompanyCutYOY,
                A.TotalAssetGrowRate,
                A.NetOperateCashFlowYOY,
                A.NOCFToOperatingNITTM,
                A.SaleServiceCashToORTTM,
                A.OperCashInToAsset,
                A.FixAssetRatio,
                A.IntangibleAssetRatio,
                A.DividendPaidRatio,
                A.RetainedEarningRatio

            from LC_MainIndexNew A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.EPS,
                B.ROE,
                B.EPSTTM,
                B.ROETTM,
                B.ROICTTM,
                B.GrossIncomeRatioTTM,
                B.NetProfitRatioTTM,
                B.PeriodCostsRateTTM,
                B.AdminiExpenseRateTTM,
                B.TotalAssetTRateTTM,
                B.ARTRate,
                B.InventoryTRate,
                B.DebtAssetsRatio,
                B.LongDebtRatio,
                B.NPParentCompanyCutYOY,
                B.TotalAssetGrowRate,
                B.NetOperateCashFlowYOY,
                B.NOCFToOperatingNITTM,
                B.SaleServiceCashToORTTM,
                B.OperCashInToAsset,
                B.FixAssetRatio,
                B.IntangibleAssetRatio,
                B.DividendPaidRatio,
                B.RetainedEarningRatio

            from LC_STIBMainIndex B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.IfAdjusted=2
        '''

f = pd.read_sql(sql_f, JY_CONN)
f = pl.from_pandas(f)
f = f.sort(["tick", "report_date", "date"]).filter(pl.col('tick').is_in(ticks)).filter(pl.col('report_date')>=pl.datetime(2007,12,31))
f = f.unique(subset=["tick", "date"], keep="last").unique(subset=["tick", "report_date"], keep="first")

In [23]:
feat_cols = [
    'EPS','ROE',
    'EPSTTM','ROETTM', 'ROICTTM', 'GrossIncomeRatioTTM', 'NetProfitRatioTTM',
    'PeriodCostsRateTTM', 'AdminiExpenseRateTTM',
    'TotalAssetTRateTTM', 'ARTRate', 'InventoryTRate',
    'DebtAssetsRatio', 'LongDebtRatio', 
    'NPParentCompanyCutYOY', 'TotalAssetGrowRate', 'NetOperateCashFlowYOY',   # 已经包含的同比变化
    'NOCFToOperatingNITTM', 'SaleServiceCashToORTTM', 'OperCashInToAsset',
    'FixAssetRatio', 'IntangibleAssetRatio',
]
f = f.select(['tick', 'report_date', 'date'] + feat_cols)

calendar = pl.DataFrame({'trade_date':dates})
df = f.sort('date').join_asof(calendar, left_on='date', right_on='trade_date', strategy='forward').sort('tick','date')
df = df.sort(['tick', 'trade_date', 'date']).unique(subset=['tick', 'trade_date'], keep='last')

date2idx = {d:i for i,d in enumerate(dates)}
tick2idx = {t:i for i,t in enumerate(ticks)}

date_idx = np.array([date2idx.get(x, -1) for x in df["trade_date"].to_list()], dtype=np.int32)
tick_idx = np.array([tick2idx.get(x, -1) for x in df["tick"].to_list()], dtype=np.int32)

df = df.with_columns([
    pl.Series("date_idx", date_idx),
    pl.Series("tick_idx", tick_idx),
]).filter(
    pl.col('date_idx').is_not_null()
)
df

shape: (226_645, 28)
┌────────┬─────────────┬─────────────┬────────┬───┬─────────────┬────────────┬──────────┬──────────┐
│ tick   ┆ report_date ┆ date        ┆ EPS    ┆ … ┆ IntangibleA ┆ trade_date ┆ date_idx ┆ tick_idx │
│ ---    ┆ ---         ┆ ---         ┆ ---    ┆   ┆ ssetRatio   ┆ ---        ┆ ---      ┆ ---      │
│ str    ┆ datetime[μs ┆ datetime[μs ┆ f64    ┆   ┆ ---         ┆ datetime[μ ┆ i32      ┆ i32      │
│        ┆ ]           ┆ ]           ┆        ┆   ┆ f64         ┆ s]         ┆          ┆          │
╞════════╪═════════════╪═════════════╪════════╪═══╪═════════════╪════════════╪══════════╪══════════╡
│ 600052 ┆ 2018-09-30  ┆ 2018-10-30  ┆ 0.1241 ┆ … ┆ 0.001829    ┆ 2018-10-30 ┆ 2633     ┆ 3066     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 002967 ┆ 2021-12-31  ┆ 2022-03-31  ┆ 0.3167 ┆ … ┆ 2.923779    ┆ 2022-03-31 ┆ 3464     ┆ 1525     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 000088 ┆ 2008-03-31  ┆ 2008-04-30  ┆ 0.0985 ┆ … ┆ 1.566833    ┆ 2008-04-30 ┆ 79       ┆ 56       │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 000513 ┆ 2022-06-30  ┆ 2022-08-10  ┆ 1.0883 ┆ … ┆ 1.342097    ┆ 2022-08-10 ┆ 3552     ┆ 111      │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 300088 ┆ 2022-03-31  ┆ 2022-04-23  ┆ 0.0739 ┆ … ┆ 1.626849    ┆ 2022-04-25 ┆ 3479     ┆ 1684     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ …      ┆ …           ┆ …           ┆ …      ┆ … ┆ …           ┆ …          ┆ …        ┆ …        │
│ 600153 ┆ 2010-06-30  ┆ 2010-08-27  ┆ 0.6331 ┆ … ┆ 0.616326    ┆ 2010-08-27 ┆ 649      ┆ 3159     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 300118 ┆ 2020-03-31  ┆ 2020-04-25  ┆ 0.1955 ┆ … ┆ 2.387955    ┆ 2020-04-27 ┆ 2996     ┆ 1713     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 605099 ┆ 2023-09-30  ┆ 2023-10-31  ┆ 0.8804 ┆ … ┆ 6.804965    ┆ 2023-10-31 ┆ 3847     ┆ 4751     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 002195 ┆ 2017-03-31  ┆ 2017-04-22  ┆ 0.0638 ┆ … ┆ 0.048545    ┆ 2017-04-24 ┆ 2262     ┆ 777      │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
│ 300392 ┆ 2020-06-30  ┆ 2020-08-29  ┆ -0.024 ┆ … ┆ 1.423483    ┆ 2020-08-31 ┆ 3081     ┆ 1986     │
│        ┆ 00:00:00    ┆ 00:00:00    ┆        ┆   ┆             ┆ 00:00:00   ┆          ┆          │
└────────┴─────────────┴─────────────┴────────┴───┴─────────────┴────────────┴──────────┴──────────┘

#### 计算yoy

In [24]:
delta_cols = [
    'EPSTTM',
    'ROETTM',
    'ROICTTM',
    'GrossIncomeRatioTTM',
    'NetProfitRatioTTM',
    'PeriodCostsRateTTM',
    'AdminiExpenseRateTTM',
    'TotalAssetTRateTTM',
    'ARTRate',
    'InventoryTRate',
    'DebtAssetsRatio',
    'LongDebtRatio',
    'NOCFToOperatingNITTM',
    'SaleServiceCashToORTTM',
    'OperCashInToAsset',
    'FixAssetRatio',
    'IntangibleAssetRatio',
]

df = df.with_columns(
    pl.col('report_date').dt.offset_by('-1y').alias('report_date_lyr')
).join(
    df, how='left', left_on=['tick','report_date_lyr'], right_on=['tick','report_date'], suffix='_lyr'
).with_columns([
    ((pl.col(c)/pl.col(c+'_lyr').replace(0,None))-1).alias(c+'_yoy')
    for c in delta_cols
]).drop(
    [c+'_lyr' for c in delta_cols]
)
df

shape: (226_645, 55)
┌────────┬────────────┬────────────┬────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ tick   ┆ report_dat ┆ date       ┆ EPS    ┆ … ┆ SaleServic ┆ OperCashIn ┆ FixAssetRa ┆ Intangibl │
│ ---    ┆ e          ┆ ---        ┆ ---    ┆   ┆ eCashToORT ┆ ToAsset_yo ┆ tio_yoy    ┆ eAssetRat │
│ str    ┆ ---        ┆ datetime[μ ┆ f64    ┆   ┆ TM_yoy     ┆ y          ┆ ---        ┆ io_yoy    │
│        ┆ datetime[μ ┆ s]         ┆        ┆   ┆ ---        ┆ ---        ┆ f64        ┆ ---       │
│        ┆ s]         ┆            ┆        ┆   ┆ f64        ┆ f64        ┆            ┆ f64       │
╞════════╪════════════╪════════════╪════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 600052 ┆ 2018-09-30 ┆ 2018-10-30 ┆ 0.1241 ┆ … ┆ 0.469948   ┆ -2.46811   ┆ -0.99298   ┆ -0.989231 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 002967 ┆ 2021-12-31 ┆ 2022-03-31 ┆ 0.3167 ┆ … ┆ 0.032167   ┆ -0.16441   ┆ -0.301695  ┆ 0.772844  │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 000088 ┆ 2008-03-31 ┆ 2008-04-30 ┆ 0.0985 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 000513 ┆ 2022-06-30 ┆ 2022-08-10 ┆ 1.0883 ┆ … ┆ 0.070506   ┆ 0.942724   ┆ -0.054685  ┆ 0.05855   │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 300088 ┆ 2022-03-31 ┆ 2022-04-23 ┆ 0.0739 ┆ … ┆ 0.06424    ┆ 1.459462   ┆ null       ┆ -0.170012 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ …      ┆ …          ┆ …          ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 600153 ┆ 2010-06-30 ┆ 2010-08-27 ┆ 0.6331 ┆ … ┆ 0.005446   ┆ -1.040578  ┆ -0.219309  ┆ -0.276065 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 300118 ┆ 2020-03-31 ┆ 2020-04-25 ┆ 0.1955 ┆ … ┆ 0.2294     ┆ -0.826968  ┆ null       ┆ -0.067794 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 605099 ┆ 2023-09-30 ┆ 2023-10-31 ┆ 0.8804 ┆ … ┆ -0.08335   ┆ -0.495992  ┆ null       ┆ -0.140867 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 002195 ┆ 2017-03-31 ┆ 2017-04-22 ┆ 0.0638 ┆ … ┆ -0.039074  ┆ -0.439187  ┆ -0.683041  ┆ -0.797982 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
│ 300392 ┆ 2020-06-30 ┆ 2020-08-29 ┆ -0.024 ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆        ┆   ┆            ┆            ┆            ┆           │
└────────┴────────────┴────────────┴────────┴───┴────────────┴────────────┴────────────┴───────────┘

#### 计算qoq

In [25]:
df = df.sort(
    ['tick','report_date']
).with_columns([
    pl.col(c).shift(1).over('tick').alias(c+'_lst')
    for c in delta_cols
]).with_columns([
    ((pl.col(c)/pl.col(c+'_lst').replace(0,None))-1).alias(c+'_qoq')
    for c in delta_cols
]).drop(
    [c+'_lst' for c in delta_cols]
)

#### 计算sue

In [28]:
sql_ff = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.OperatingRevenue/10000 as "or",
                A.OperatingProfit/10000 as "op",
                A.TotalProfit/10000 as "tp",
                A.NetProfit/10000 as "np"

            from LC_IncomeStatementAll A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and A.IfMerged=1
                and A.IfAdjusted=2
                and A.BulletinType=20

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.OperatingRevenue/10000 as "or",
                B.OperatingProfit/10000 as "op",
                B.TotalProfit/10000 as "tp",
                B.NetProfit/10000 as "np"
            from LC_STIBIncomeState B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.IfAdjusted=2
        '''

ff = pd.read_sql(sql_ff, JY_CONN)
ff = pl.from_pandas(ff)
ff = ff.sort(["tick", "report_date", "date"]).filter(pl.col('tick').is_in(ticks)).filter(pl.col('report_date')>=pl.datetime(2007,12,31))
ff = ff.unique(subset=["tick", "date"], keep="last").unique(subset=["tick", "report_date"], keep="first")

In [29]:
dff = df.join(
    ff, how='left', on=['tick','report_date']
).drop('date_right')
dff

shape: (226_645, 76)
┌────────┬───────────────┬──────────────┬────────┬───┬────────────┬──────────┬──────────┬──────────┐
│ tick   ┆ report_date   ┆ date         ┆ EPS    ┆ … ┆ or         ┆ op       ┆ tp       ┆ np       │
│ ---    ┆ ---           ┆ ---          ┆ ---    ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ datetime[μs]  ┆ datetime[μs] ┆ f64    ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪══════════════╪════════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ 000001 ┆ 2007-12-31    ┆ 2008-03-20   ┆ 1.1554 ┆ … ┆ 1080750.2  ┆ 372194.2 ┆ 377177.5 ┆ 264990.3 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-03-31    ┆ 2008-04-24   ┆ 0.4379 ┆ … ┆ 355327.0   ┆ 137635.1 ┆ 137910.5 ┆ 100418.2 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-06-30    ┆ 2008-08-21   ┆ 0.8975 ┆ … ┆ 711525.3   ┆ 284099.6 ┆ 282566.8 ┆ 214383.4 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-09-30    ┆ 2008-10-24   ┆ 1.3886 ┆ … ┆ 1074140.6  ┆ 436420.4 ┆ 431466.9 ┆ 331699.4 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 000001 ┆ 2008-12-31    ┆ 2009-03-20   ┆ 0.1977 ┆ … ┆ 1451311.9  ┆ 80342.6  ┆ 79260.9  ┆ 61403.5  │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ …      ┆ …             ┆ …            ┆ …      ┆ … ┆ …          ┆ …        ┆ …        ┆ …        │
│ 688981 ┆ 2024-09-30    ┆ 2024-11-08   ┆ 0.3395 ┆ … ┆ 4.187872e6 ┆ 355244.5 ┆ 355369.2 ┆ 323266.0 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2024-12-31    ┆ 2025-03-28   ┆ 0.4637 ┆ … ┆ 5.779557e6 ┆ 629864.7 ┆ 629202.2 ┆ 537311.8 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-03-31    ┆ 2025-05-09   ┆ 0.1699 ┆ … ┆ 1630108.5  ┆ 247946.9 ┆ 248217.9 ┆ 232091.5 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-06-30    ┆ 2025-08-29   ┆ 0.2881 ┆ … ┆ 3234804.9  ┆ 363656.9 ┆ 362659.3 ┆ 336767.8 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
│ 688981 ┆ 2025-09-30    ┆ 2025-11-14   ┆ 0.4773 ┆ … ┆ 4951041.6  ┆ 618976.0 ┆ 618323.1 ┆ 577035.9 │
│        ┆ 00:00:00      ┆ 00:00:00     ┆        ┆   ┆            ┆          ┆          ┆          │
└────────┴───────────────┴──────────────┴────────┴───┴────────────┴──────────┴──────────┴──────────┘

In [12]:
from sqlalchemy.engine import URL

zyyx_url = URL.create(drivername="mssql+pymssql",
             username="zyyxReader",
             password="zyyx!5893@Fund",
             host="10.110.0.106",
             database="zyyx",)
             #query={"charset": "gb18030"})
# 如果需要在连接时指定 tds_version，可以这样处理
zyyx_engine = create_engine(
    zyyx_url,
    connect_args={
        "tds_version": "7.0",
        #"charset": "gb18030"
    }
)

zyyx_conn = zyyx_engine.connect()

In [59]:
con_sql = f"""
select 
    create_date as "con_infodate", 
    stock_code as "tick", 
    report_year,
    report_quarter,
    author_name,
    forecast_or,
    forecast_op,
    forecast_np,
    forecast_tp,
    forecast_roe,
    forecast_eps
from rpt_forecast_stk
where create_date <='{end_dt}'
"""
raw_con = pl.read_database(con_sql, zyyx_conn).sort(['tick','con_infodate'])

# 删除全null行
con = raw_con.filter(pl.col('report_year').is_not_null() & pl.col('report_quarter').is_not_null())

# 生成预测的报告日期
con = con.with_columns(
    pl.col("report_quarter").mul(3).alias("month"),
).with_columns(
    (pl.date(pl.col("report_year"), pl.col("month"), 1)
     .dt.offset_by("1mo")
     .dt.offset_by("-1d")
    ).alias("report_date")
).with_columns(
    pl.col("report_date").dt.to_string("%Y-%m-%d").alias("report_date")
).drop(['report_year','report_quarter','month'])

con = con.sort(['tick','report_date']).with_columns([
    pl.col('con_infodate').str.to_datetime(),
    pl.col('report_date').str.to_datetime(),
])

# 处理单独分析师一行, 然后按报告期去重取最新预测
con = (
    con.with_columns(
        pl.col("author_name")
        .str.replace_all(r"[、，]", ",")
        .str.split(",")
        .alias("author_list")
    )
    .explode("author_list")
    .drop("author_name")              # 删除旧列
    .rename({"author_list": "author_name"})  # 重命名
)
con = con.with_columns(
    pl.col("author_name").cast(pl.Categorical).to_physical().alias("author_id")
).drop('author_name')

con = (
    con
    .sort(by=["report_date", "author_id", "con_infodate"], descending=[False, False, True])
    .group_by(["report_date", "author_id"])
    .first()
)

# 生成上一报告期
con = con.join(
    dff.select(['tick','report_date','date']).sort(['tick','date']).with_columns(pl.col('date').shift(1).alias('date_lst')),
    how='left', on=['tick','report_date']
)

# 确保分析师预期发布，在两个发布日之间
con = con.filter( 
    (pl.col('con_infodate')>pl.col('date_lst')) & (pl.col('con_infodate')<pl.col('date'))
)
con

shape: (26_988, 12)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ report_dat ┆ author_id ┆ con_infoda ┆ tick   ┆ … ┆ forecast_ ┆ forecast_ ┆ date      ┆ date_lst  │
│ e          ┆ ---       ┆ te         ┆ ---    ┆   ┆ roe       ┆ eps       ┆ ---       ┆ ---       │
│ ---        ┆ u32       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ datetime[ │
│ datetime[μ ┆           ┆ datetime[μ ┆        ┆   ┆ f64       ┆ f64       ┆ μs]       ┆ μs]       │
│ s]         ┆           ┆ s]         ┆        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2010-12-31 ┆ 1314      ┆ 2011-04-14 ┆ 600098 ┆ … ┆ 5.9       ┆ 0.32      ┆ 2011-04-2 ┆ 2010-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 0         ┆ 8         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2009-12-31 ┆ 6491      ┆ 2010-01-18 ┆ 000978 ┆ … ┆ 6.7       ┆ 0.222034  ┆ 2010-03-2 ┆ 2009-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 6         ┆ 9         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2015-12-31 ┆ 3937      ┆ 2015-12-21 ┆ 600487 ┆ … ┆ 11.7      ┆ 0.43      ┆ 2016-04-0 ┆ 2015-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 6         ┆ 1         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2012-12-31 ┆ 13506     ┆ 2013-03-24 ┆ 601628 ┆ … ┆ null      ┆ 0.39      ┆ 2013-03-2 ┆ 2012-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 8         ┆ 7         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2020-03-31 ┆ 5327      ┆ 2020-04-08 ┆ 603369 ┆ … ┆ null      ┆ 0.534     ┆ 2020-04-2 ┆ 2019-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 9         ┆ 1         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ …          ┆ …         ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2010-12-31 ┆ 12007     ┆ 2011-02-01 ┆ 300027 ┆ … ┆ null      ┆ 0.4462    ┆ 2011-03-1 ┆ 2010-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 1         ┆ 7         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2012-12-31 ┆ 4704      ┆ 2013-03-04 ┆ 300104 ┆ … ┆ 14.42     ┆ 0.47      ┆ 2013-03-0 ┆ 2012-10-2 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 8         ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2014-12-31 ┆ 6133      ┆ 2014-11-05 ┆ 002419 ┆ … ┆ 10.8      ┆ 0.65      ┆ 2015-03-1 ┆ 2014-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 1         ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2016-12-31 ┆ 1528      ┆ 2017-04-26 ┆ 000651 ┆ … ┆ 28.63     ┆ 2.56      ┆ 2017-04-2 ┆ 2016-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 7         ┆ 1         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 2019-12-31 ┆ 613       ┆ 2020-03-31 ┆ 001914 ┆ … ┆ null      ┆ 0.27      ┆ 2020-04-1 ┆ 2019-10-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆ 4         ┆ 1         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [77]:
sue_cols = [
    'forecast_or',
    'forecast_op',
    'forecast_np',
    'forecast_tp',
    'forecast_roe',
    'forecast_eps'
]

con_res = (
    con
    .with_columns([
        pl.col(c).median().over(['tick','report_date']).alias(c)
        for c in sue_cols
    ])
    .drop("author_id")   # 如果你的列名是 authorid / author_id，就改成实际列名
    .unique(
        subset=['tick','report_date'],
        keep="first",
        maintain_order=True,
    )
).drop(['con_infodate','date_lst']).sort(['tick','report_date'])

In [ ]:
dff = dff.rename({'ROE':'roe', 'EPS':'eps'})
dff = dff.join(
    con_res, how='left', on=['tick','report_date']
)

In [ ]:
sue_base_cols = ['or','op','tp','np','roe','eps']
final = dff.with_columns([
    (pl.col(c)-pl.col('forecast_'+c)).alias(c+'_ue')
    for c in sue_base_cols
]).sort(['tick','report_date']).with_columns([
    pl.col(c).shift(1).rolling_std(window_size=12, min_periods=1, ddof=0).over('tick').alias(f'{c}_uestd')
    for c in sue_base_cols
]).with_columns([
    (pl.col(c+'_ue') / pl.col(c+'_uestd').replace(0, None)).alias(c+'_sue')
    for c in sue_base_cols
])

shape: (226_645, 101)
┌────────┬───────────────┬───────────────┬────────┬───┬──────────┬──────────┬───────────┬──────────┐
│ tick   ┆ report_date   ┆ date          ┆ eps    ┆ … ┆ tp_sue   ┆ np_sue   ┆ roe_sue   ┆ eps_sue  │
│ ---    ┆ ---           ┆ ---           ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ str    ┆ datetime[μs]  ┆ datetime[μs]  ┆ f64    ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
╞════════╪═══════════════╪═══════════════╪════════╪═══╪══════════╪══════════╪═══════════╪══════════╡
│ 000001 ┆ 2007-12-31    ┆ 2008-03-20    ┆ 1.1554 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-03-31    ┆ 2008-04-24    ┆ 0.4379 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-06-30    ┆ 2008-08-21    ┆ 0.8975 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-09-30    ┆ 2008-10-24    ┆ 1.3886 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-12-31    ┆ 2009-03-20    ┆ 0.1977 ┆ … ┆ -0.18354 ┆ 0.016603 ┆ -0.003922 ┆ 0.012726 │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ …      ┆ …             ┆ …             ┆ …      ┆ … ┆ …        ┆ …        ┆ …         ┆ …        │
│ 688981 ┆ 2024-09-30    ┆ 2024-11-08    ┆ 0.3395 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2024-12-31    ┆ 2025-03-28    ┆ 0.4637 ┆ … ┆ 0.026047 ┆ 0.387388 ┆ -0.099344 ┆ 0.007929 │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-03-31    ┆ 2025-05-09    ┆ 0.1699 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-06-30    ┆ 2025-08-29    ┆ 0.2881 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-09-30    ┆ 2025-11-14    ┆ 0.4773 ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00      ┆ 00:00:00      ┆        ┆   ┆          ┆          ┆           ┆          │
└────────┴───────────────┴───────────────┴────────┴───┴──────────┴──────────┴───────────┴──────────┘

In [83]:
feat_cols = [
    'NPParentCompanyCutYOY','TotalAssetGrowRate','NetOperateCashFlowYOY'
]+[
    c+'_yoy' for c in delta_cols
]+[
    c+'_qoq' for c in delta_cols
]+[
    c+'_sue' for c in sue_base_cols
]
idx_cols = ['tick','report_date','date','tick_idx','date_idx']

final = final.select(idx_cols+feat_cols)
final

shape: (226_645, 48)
┌────────┬──────────────┬──────────────┬──────────┬───┬──────────┬──────────┬───────────┬──────────┐
│ tick   ┆ report_date  ┆ date         ┆ tick_idx ┆ … ┆ tp_sue   ┆ np_sue   ┆ roe_sue   ┆ eps_sue  │
│ ---    ┆ ---          ┆ ---          ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ str    ┆ datetime[μs] ┆ datetime[μs] ┆ i32      ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
╞════════╪══════════════╪══════════════╪══════════╪═══╪══════════╪══════════╪═══════════╪══════════╡
│ 000001 ┆ 2007-12-31   ┆ 2008-03-20   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-03-31   ┆ 2008-04-24   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-06-30   ┆ 2008-08-21   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-09-30   ┆ 2008-10-24   ┆ 0        ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 000001 ┆ 2008-12-31   ┆ 2009-03-20   ┆ 0        ┆ … ┆ -0.18354 ┆ 0.016603 ┆ -0.003922 ┆ 0.012726 │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ …      ┆ …            ┆ …            ┆ …        ┆ … ┆ …        ┆ …        ┆ …         ┆ …        │
│ 688981 ┆ 2024-09-30   ┆ 2024-11-08   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2024-12-31   ┆ 2025-03-28   ┆ 5435     ┆ … ┆ 0.026047 ┆ 0.387388 ┆ -0.099344 ┆ 0.007929 │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-03-31   ┆ 2025-05-09   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-06-30   ┆ 2025-08-29   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
│ 688981 ┆ 2025-09-30   ┆ 2025-11-14   ┆ 5435     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│        ┆ 00:00:00     ┆ 00:00:00     ┆          ┆   ┆          ┆          ┆           ┆          │
└────────┴──────────────┴──────────────┴──────────┴───┴──────────┴──────────┴───────────┴──────────┘