In [1]:
import os
import sys

# 将项目根目录加入 sys.path（根据实际情况修改路径）
project_root = os.path.abspath('..')   # 或 os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 然后绝对导入
from utils import Processor, Calculator

In [2]:
import os
import polars as pl
import numpy as np
import torch
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time
from sqlalchemy import create_engine
import pymssql
from typing import List, Dict

import warnings
warnings.filterwarnings('ignore')

In [3]:
T,N = 3400, 5422
start_dt = '2008-01-01'     
end_dt = '2025-12-31'

ROOT = '/data/xujiayi/end2end/'

JY_CONFIG = {
    "server": '10.10.0.102',
    "user": 'jydbReader',
    "password": 'jy@9043!Reader',
    "database": 'jydb',
    "charset": 'cp936'
}
JY_CONN = pymssql.connect(**JY_CONFIG)

STR_CONN = create_engine('mysql+pymysql://QuantReader:Quant%40Reader%21zsfund.com@10.10.6.101:9030/HighFrequency')

In [4]:
dates = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)

close = np.memmap('/data/xujiayi/end2end/d_field/close.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
nan_mask = np.isnan(close)

In [5]:
base_types = [110101,110102,110103,110104]
base_types_str = ','.join(str(t) for t in base_types)

In [ ]:
# 获取利润表字段
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.BasicEPS as "basic_eps",
                A.TotalOperatingRevenue as "total_operating_revenue",
                A.NPParentCompanyOwners as "np_parent_company_owners",
                A.OperatingCost as "operating_cost",
                A.NetProfit as "net_profit"
            from LC_IncomeStatementAll A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and A.InfoSourceCode in ({base_types_str})
                and A.IfMerged=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.BasicEPS as "basic_eps",
                B.TotalOperatingRevenue as "total_operating_revenue",
                B.NPParentCompanyOwners as "np_parent_company_owners",
                B.OperatingCost as "operating_cost",
                B.NetProfit as "net_profit"
            from LC_STIBIncomeState B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.InfoSourceCode in ({base_types_str})
        '''

f = pl.read_database(sql_f, JY_CONN)
f = f.sort(["tick", "report_date", "date"]).unique(subset=["tick", "date"], keep="last")
f = f.sort(['tick', 'report_date', 'date']).unique(subset=["tick", "report_date"], keep="first")
f = f.sort(['tick', 'report_date'])

In [136]:
# 计算利润表衍生字段
f = f.with_columns([
    ((pl.col('total_operating_revenue') - pl.col('operating_cost')) / pl.col('total_operating_revenue').replace(0, None)).alias('gpm'),
    (pl.col('net_profit') / pl.col('total_operating_revenue').replace(0, None)).alias('npm')
])

In [137]:
# 获取资产负债表字段
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.SEWithoutMI as "se_without_m_i",
                A.TotalLiability as "total_liability",
                A.TotalAssets as "total_assets"
            from LC_BalanceSheetAll A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and A.InfoSourceCode in ({base_types_str})
                and A.IfMerged=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.SEWithoutMI as "se_without_m_i",
                B.TotalLiability as "total_liability",
                B.TotalAssets as "total_assets"
            from LC_STIBBalanceSheet B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.InfoSourceCode in ({base_types_str})
        '''

f_bs = pl.read_database(sql_f, JY_CONN)
f_bs = f_bs.sort(["tick", "report_date", "date"]).unique(subset=["tick", "date"], keep="last")
f_bs = f_bs.sort(['tick','report_date','date']).unique(subset=["tick", "report_date"], keep="first")
f_bs = f_bs.sort(['tick','report_date'])

In [142]:
f_merge = f.join(
    f_bs,
    how='inner',
    on=['report_date','tick','date']
)
f_merge

shape: (271_338, 13)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ date       ┆ basic_eps ┆ … ┆ npm       ┆ se_withou ┆ total_lia ┆ total_ass │
│ ---    ┆ e          ┆ ---        ┆ ---       ┆   ┆ ---       ┆ t_m_i     ┆ bility    ┆ ets       │
│ str    ┆ ---        ┆ datetime[μ ┆ decimal[3 ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│        ┆ datetime[μ ┆ s]         ┆ 8,4]      ┆   ┆ 8,4]      ┆ decimal[3 ┆ decimal[3 ┆ decimal[3 │
│        ┆ s]         ┆            ┆           ┆   ┆           ┆ 8,4]      ┆ 8,4]      ┆ 8,4]      │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 1991-12-31 ┆ 1992-03-08 ┆ null      ┆ … ┆ 0.3831    ┆ 73484150. ┆ null      ┆ 435445599 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 0300      ┆           ┆ 3.3200    │
│ 000001 ┆ 1993-12-31 ┆ 1994-04-16 ┆ null      ┆ … ┆ 0.3387    ┆ 120459258 ┆ 811440711 ┆ 932322444 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 7.5600    ┆ 0.5900    ┆ 8.8900    │
│ 000001 ┆ 1994-12-31 ┆ 1995-03-10 ┆ null      ┆ … ┆ 0.2563    ┆ 165560820 ┆ 138285790 ┆ 154884119 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 5.2800    ┆ 26.5200   ┆ 82.5400   │
│ 000001 ┆ 1995-06-30 ┆ 1995-08-11 ┆ null      ┆ … ┆ 0.2570    ┆ 186410158 ┆ 155716040 ┆ 174399303 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 7.3200    ┆ 45.4800   ┆ 83.5400   │
│ 000001 ┆ 1995-12-31 ┆ 1996-03-14 ┆ null      ┆ … ┆ 0.2067    ┆ 195546101 ┆ 183519366 ┆ 203124755 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 0.6500    ┆ 28.2300   ┆ 61.4300   │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ X25198 ┆ 2021-12-31 ┆ 2022-04-28 ┆ null      ┆ … ┆ 0.0065    ┆ 154807930 ┆ 648959145 ┆ 817336504 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 2.1300    ┆ 8.3300    ┆ 9.5000    │
│ X25202 ┆ 2014-03-31 ┆ 2014-04-30 ┆ null      ┆ … ┆ 0.0056    ┆ 789697769 ┆ 227705965 ┆ 306675742 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ .6300     ┆ 6.1400    ┆ 5.7700    │
│ X25202 ┆ 2014-06-30 ┆ 2014-08-22 ┆ null      ┆ … ┆ 0.1320    ┆ 830398752 ┆ 240813755 ┆ 323853630 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ .1800     ┆ 3.5100    ┆ 5.6900    │
│ X25202 ┆ 2014-09-30 ┆ 2014-10-20 ┆ null      ┆ … ┆ 0.1312    ┆ 851406751 ┆ 224017379 ┆ 309158054 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ .4600     ┆ 5.5400    ┆ 7.0000    │
│ X25216 ┆ 2023-06-30 ┆ 2023-08-31 ┆ null      ┆ … ┆ 0.0871    ┆ 188529931 ┆ 851025030 ┆ 273632435 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆ 9.2700    ┆ .9400     ┆ 0.2100    │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [143]:
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.NetOperateCashFlow as "net_operate_cash_flow"
            from LC_CashFlowStatementAll A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and A.InfoSourceCode in ({base_types_str})
                and A.IfMerged=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.NetOperateCashFlow as "net_operate_cash_flow"
            from LC_STIBCashFlowState B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.InfoSourceCode in ({base_types_str})
                and B.IfMerged=1
        '''

f_cfs = pl.read_database(sql_f, JY_CONN)
f_cfs = f_cfs.sort(["tick", "report_date", "date"]).unique(subset=["tick", "date"], keep="last")
f_cfs = f_cfs.sort(['tick','report_date','date']).unique(subset=["tick", "report_date"], keep="last")
f_cfs = f_cfs.sort(['tick','report_date'])

In [144]:
f_merge2 = f_merge.join(
    f_cfs,
    how='inner',
    on=['report_date','tick','date']
)
f_merge2

shape: (262_049, 14)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ date       ┆ basic_eps ┆ … ┆ se_withou ┆ total_lia ┆ total_ass ┆ net_opera │
│ ---    ┆ e          ┆ ---        ┆ ---       ┆   ┆ t_m_i     ┆ bility    ┆ ets       ┆ te_cash_f │
│ str    ┆ ---        ┆ datetime[μ ┆ decimal[3 ┆   ┆ ---       ┆ ---       ┆ ---       ┆ low       │
│        ┆ datetime[μ ┆ s]         ┆ 8,4]      ┆   ┆ decimal[3 ┆ decimal[3 ┆ decimal[3 ┆ ---       │
│        ┆ s]         ┆            ┆           ┆   ┆ 8,4]      ┆ 8,4]      ┆ 8,4]      ┆ decimal[3 │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ 8,4]      │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 1998-06-30 ┆ 1998-08-26 ┆ null      ┆ … ┆ 377227098 ┆ 310963982 ┆ 348733722 ┆ 158155570 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 2.4000    ┆ 40.0300   ┆ 70.7500   ┆ 1.2300    │
│ 000001 ┆ 1998-12-31 ┆ 1999-04-23 ┆ null      ┆ … ┆ 367664829 ┆ 357234953 ┆ 393998586 ┆ 229109784 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 2.9200    ┆ 76.9900   ┆ 17.2600   ┆ 2.5500    │
│ 000001 ┆ 1999-06-30 ┆ 1999-07-17 ┆ null      ┆ … ┆ 391754928 ┆ 347945637 ┆ 387121129 ┆ 421788125 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 0.5100    ┆ 18.7200   ┆ 99.2300   ┆ .4400     │
│ 000001 ┆ 1999-12-31 ┆ 2000-04-19 ┆ null      ┆ … ┆ 290083070 ┆ 429681413 ┆ 458689720 ┆ 467159447 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 6.0000    ┆ 44.0000   ┆ 50.0000   ┆ 4.0000    │
│ 000001 ┆ 2000-06-30 ┆ 2000-07-26 ┆ null      ┆ … ┆ 307851255 ┆ 466538239 ┆ 497323365 ┆ 172340380 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 6.0000    ┆ 60.0000   ┆ 16.0000   ┆ .0000     │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ X25198 ┆ 2021-12-31 ┆ 2022-04-28 ┆ null      ┆ … ┆ 154807930 ┆ 648959145 ┆ 817336504 ┆ 174659488 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 2.1300    ┆ 8.3300    ┆ 9.5000    ┆ .2600     │
│ X25202 ┆ 2014-03-31 ┆ 2014-04-30 ┆ null      ┆ … ┆ 789697769 ┆ 227705965 ┆ 306675742 ┆ 17517957. │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ .6300     ┆ 6.1400    ┆ 5.7700    ┆ 6100      │
│ X25202 ┆ 2014-06-30 ┆ 2014-08-22 ┆ null      ┆ … ┆ 830398752 ┆ 240813755 ┆ 323853630 ┆ 159087663 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ .1800     ┆ 3.5100    ┆ 5.6900    ┆ .8500     │
│ X25202 ┆ 2014-09-30 ┆ 2014-10-20 ┆ null      ┆ … ┆ 851406751 ┆ 224017379 ┆ 309158054 ┆ 19377929. │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ .4600     ┆ 5.5400    ┆ 7.0000    ┆ 2100      │
│ X25216 ┆ 2023-06-30 ┆ 2023-08-31 ┆ null      ┆ … ┆ 188529931 ┆ 851025030 ┆ 273632435 ┆ 269593343 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 9.2700    ┆ .9400     ┆ 0.2100    ┆ .3900     │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [145]:
f_merge2 = f_merge2.with_columns([
    (pl.col('np_parent_company_owners') / pl.col('se_without_m_i').replace(0, None)).alias('roe'),
    (pl.col('total_liability')/ pl.col('total_assets').replace(0, None)).alias('l2a')
])
f_merge2

shape: (262_049, 16)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ date       ┆ basic_eps ┆ … ┆ total_ass ┆ net_opera ┆ roe       ┆ l2a       │
│ ---    ┆ e          ┆ ---        ┆ ---       ┆   ┆ ets       ┆ te_cash_f ┆ ---       ┆ ---       │
│ str    ┆ ---        ┆ datetime[μ ┆ decimal[3 ┆   ┆ ---       ┆ low       ┆ decimal[3 ┆ decimal[3 │
│        ┆ datetime[μ ┆ s]         ┆ 8,4]      ┆   ┆ decimal[3 ┆ ---       ┆ 8,4]      ┆ 8,4]      │
│        ┆ s]         ┆            ┆           ┆   ┆ 8,4]      ┆ decimal[3 ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ 8,4]      ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 1998-06-30 ┆ 1998-08-26 ┆ null      ┆ … ┆ 348733722 ┆ 158155570 ┆ 0.1002    ┆ 0.8917    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 70.7500   ┆ 1.2300    ┆           ┆           │
│ 000001 ┆ 1998-12-31 ┆ 1999-04-23 ┆ null      ┆ … ┆ 393998586 ┆ 229109784 ┆ 0.2079    ┆ 0.9067    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 17.2600   ┆ 2.5500    ┆           ┆           │
│ 000001 ┆ 1999-06-30 ┆ 1999-07-17 ┆ null      ┆ … ┆ 387121129 ┆ 421788125 ┆ 0.0615    ┆ 0.8988    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 99.2300   ┆ .4400     ┆           ┆           │
│ 000001 ┆ 1999-12-31 ┆ 2000-04-19 ┆ null      ┆ … ┆ 458689720 ┆ 467159447 ┆ 0.1914    ┆ 0.9368    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 50.0000   ┆ 4.0000    ┆           ┆           │
│ 000001 ┆ 2000-06-30 ┆ 2000-07-26 ┆ null      ┆ … ┆ 497323365 ┆ 172340380 ┆ 0.0578    ┆ 0.9381    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 16.0000   ┆ .0000     ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ X25198 ┆ 2021-12-31 ┆ 2022-04-28 ┆ null      ┆ … ┆ 817336504 ┆ 174659488 ┆ 0.0351    ┆ 0.7940    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 9.5000    ┆ .2600     ┆           ┆           │
│ X25202 ┆ 2014-03-31 ┆ 2014-04-30 ┆ null      ┆ … ┆ 306675742 ┆ 17517957. ┆ 0.0009    ┆ 0.7425    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 5.7700    ┆ 6100      ┆           ┆           │
│ X25202 ┆ 2014-06-30 ┆ 2014-08-22 ┆ null      ┆ … ┆ 323853630 ┆ 159087663 ┆ 0.0479    ┆ 0.7436    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 5.6900    ┆ .8500     ┆           ┆           │
│ X25202 ┆ 2014-09-30 ┆ 2014-10-20 ┆ null      ┆ … ┆ 309158054 ┆ 19377929. ┆ 0.0693    ┆ 0.7246    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 7.0000    ┆ 2100      ┆           ┆           │
│ X25216 ┆ 2023-06-30 ┆ 2023-08-31 ┆ null      ┆ … ┆ 273632435 ┆ 269593343 ┆ 0.0554    ┆ 0.3110    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 0.2100    ┆ .3900     ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [146]:
f_merge2 = f_merge2.rename({'date':'sheet_infodate'})

In [151]:
from sqlalchemy.engine import URL

zyyx_url = URL.create(drivername="mssql+pymssql",
             username="zyyxReader",
             password="zyyx!5893@Fund",
             host="10.110.0.106",
             database="zyyx",)
             #query={"charset": "gb18030"})
# 如果需要在连接时指定 tds_version，可以这样处理
zyyx_engine = create_engine(
    zyyx_url,
    connect_args={
        "tds_version": "7.0",
        #"charset": "gb18030"
    }
)

zyyx_conn = zyyx_engine.connect()

In [152]:
con_sql = f"""
select 
    create_date as "con_infodate", 
    stock_code as "tick", 
    report_year,
    report_quarter,
    author_name,
    forecast_or,
    forecast_op,
    forecast_np,
    forecast_roe,
    forecast_eps,
    forecast_pe
from rpt_forecast_stk
where create_date <='{end_dt}'
"""
raw_con = pl.read_database(con_sql, zyyx_conn).sort(['tick','con_infodate'])

In [161]:
# 删除全null行
all_cols = raw_con.columns
cols_to_check = [c for c in all_cols if c not in ["con_infodate", "tick",'author_name']]
con = raw_con.filter(
    pl.any_horizontal([pl.col(c).is_not_null() for c in cols_to_check])
)
con

shape: (4_027_843, 11)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ con_infoda ┆ tick   ┆ report_yea ┆ report_qu ┆ … ┆ forecast_ ┆ forecast_ ┆ forecast_ ┆ forecast_ │
│ te         ┆ ---    ┆ r          ┆ arter     ┆   ┆ np        ┆ roe       ┆ eps       ┆ pe        │
│ ---        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆        ┆ i64        ┆ i64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2006-01-10 ┆ 000001 ┆ 2005       ┆ 4         ┆ … ┆ 30985.1   ┆ 6.41      ┆ 0.16      ┆ null      │
│ 2006-01-10 ┆ 000001 ┆ 2006       ┆ 4         ┆ … ┆ 33625.2   ┆ 6.55      ┆ 0.17      ┆ null      │
│ 2006-04-02 ┆ 000001 ┆ 2007       ┆ 4         ┆ … ┆ 71000.0   ┆ 10.07     ┆ 0.364884  ┆ null      │
│ 2006-04-02 ┆ 000001 ┆ 2008       ┆ 4         ┆ … ┆ 103800.0  ┆ 12.82     ┆ 0.533451  ┆ null      │
│ 2006-04-02 ┆ 000001 ┆ 2006       ┆ 4         ┆ … ┆ 49500.0   ┆ 7.79      ┆ 0.254391  ┆ null      │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025-10-30 ┆ 920992 ┆ 2026       ┆ 4         ┆ … ┆ 2955.0    ┆ 4.55      ┆ 0.31      ┆ 70.9      │
│ 2025-10-30 ┆ 920992 ┆ 2025       ┆ 4         ┆ … ┆ 2522.0    ┆ 4.01      ┆ 0.26      ┆ 83.08     │
│ 2025-11-09 ┆ 920992 ┆ 2026       ┆ 4         ┆ … ┆ 1939.0    ┆ 3.07      ┆ 0.2       ┆ 102.34    │
│ 2025-11-09 ┆ 920992 ┆ 2025       ┆ 4         ┆ … ┆ 1810.0    ┆ 2.92      ┆ 0.19      ┆ 109.61    │
│ 2025-11-09 ┆ 920992 ┆ 2027       ┆ 4         ┆ … ┆ 2465.0    ┆ 3.83      ┆ 0.25      ┆ 80.49     │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [162]:
# 生成预测的报告日期
con = con.with_columns(
    pl.col("report_quarter").mul(3).alias("month"),
).with_columns(
    (pl.date(pl.col("report_year"), pl.col("month"), 1)
     .dt.offset_by("1mo")
     .dt.offset_by("-1d")
    ).alias("report_date")
).with_columns(
    pl.col("report_date").dt.to_string("%Y-%m-%d").alias("report_date")
).drop(['report_year','report_quarter','month'])

con = con.sort(['tick','report_date']).with_columns([
    pl.col('con_infodate').str.to_datetime(),
    pl.col('report_date').str.to_datetime(),
])
con

shape: (4_027_843, 10)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ con_infoda ┆ tick   ┆ author_nam ┆ forecast_ ┆ … ┆ forecast_ ┆ forecast_ ┆ forecast_ ┆ report_da │
│ te         ┆ ---    ┆ e          ┆ or        ┆   ┆ roe       ┆ eps       ┆ pe        ┆ te        │
│ ---        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ datetime[μ ┆        ┆ str        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ datetime[ │
│ s]         ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2006-01-10 ┆ 000001 ┆ ÑîÇàÀö     ┆ 887603.1  ┆ … ┆ 6.41      ┆ 0.16      ┆ null      ┆ 2005-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2006-10-18 ┆ 000001 ┆ ÎéÓÀ¸Õ     ┆ null      ┆ … ┆ null      ┆ 0.430618  ┆ null      ┆ 2006-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2006-01-10 ┆ 000001 ┆ ÑîÇàÀö     ┆ 1014599.2 ┆ … ┆ 6.55      ┆ 0.17      ┆ null      ┆ 2006-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2007-03-02 ┆ 000001 ┆ ·¶ÑÞèª     ┆ null      ┆ … ┆ 21.05823  ┆ 0.6929    ┆ null      ┆ 2006-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2006-04-02 ┆ 000001 ┆ ÎéÓÀ¸Õ     ┆ 1.0975e6  ┆ … ┆ 7.79      ┆ 0.254391  ┆ null      ┆ 2006-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025-11-09 ┆ 920992 ┆ Áú¾¸Äþ     ┆ 33437.0   ┆ … ┆ 3.07      ┆ 0.2       ┆ 102.34    ┆ 2026-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2025-09-02 ┆ 920992 ┆ Öîº£±õ     ┆ 41900.0   ┆ … ┆ 6.0       ┆ 0.42      ┆ 52.3      ┆ 2027-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2025-10-25 ┆ 920992 ┆ Öîº£±õ     ┆ 41900.0   ┆ … ┆ 6.0       ┆ 0.42      ┆ 52.5      ┆ 2027-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2025-10-30 ┆ 920992 ┆ Îâ´ººì     ┆ 40646.0   ┆ … ┆ 4.87      ┆ 0.34      ┆ 64.08     ┆ 2027-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2025-11-09 ┆ 920992 ┆ Áú¾¸Äþ     ┆ 36844.0   ┆ … ┆ 3.83      ┆ 0.25      ┆ 80.49     ┆ 2027-12-3 │
│ 00:00:00   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 00:00:00  │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [163]:
# 处理单独分析师一行, 然后按报告期去重
con = (
    con.with_columns(
        pl.col("author_name")
        .str.replace_all(r"[、，]", ",")
        .str.split(",")
        .alias("author_list")
    )
    .explode("author_list")
    .drop("author_name")              # 删除旧列
    .rename({"author_list": "author_name"})  # 重命名
)
con = con.with_columns(
    pl.col("author_name").cast(pl.Categorical).to_physical().alias("author_id")
).drop('author_name')

con = (
    con
    .sort(by=["report_date", "author_id", "con_infodate"], descending=[False, False, True])
    .group_by(["report_date", "author_id"])
    .first()
)

con

shape: (94_393, 10)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ report_dat ┆ author_id ┆ con_infoda ┆ tick   ┆ … ┆ forecast_ ┆ forecast_ ┆ forecast_ ┆ forecast_ │
│ e          ┆ ---       ┆ te         ┆ ---    ┆   ┆ np        ┆ roe       ┆ eps       ┆ pe        │
│ ---        ┆ u32       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ datetime[μ ┆           ┆ datetime[μ ┆        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│ s]         ┆           ┆ s]         ┆        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2027-12-31 ┆ 5430      ┆ 2025-12-18 ┆ 301397 ┆ … ┆ 23816.423 ┆ null      ┆ 1.53      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2017-12-31 ┆ 318       ┆ 2018-01-25 ┆ 601939 ┆ … ┆ 2.46089e7 ┆ 15.03     ┆ 0.98      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2026-12-31 ┆ 12902     ┆ 2025-09-30 ┆ 600406 ┆ … ┆ 951900.0  ┆ 17.5      ┆ 1.19      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2010-12-31 ┆ 10443     ┆ 2009-06-03 ┆ 002007 ┆ … ┆ 33739.0   ┆ null      ┆ 0.94      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2025-12-31 ┆ 11505     ┆ 2024-11-09 ┆ 688150 ┆ … ┆ 32139.0   ┆ 15.53     ┆ 0.8       ┆ 30.08     │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-12-31 ┆ 5335      ┆ 2025-10-30 ┆ 000333 ┆ … ┆ 4.8558e6  ┆ 20.4      ┆ 6.32      ┆ 11.7      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2018-12-31 ┆ 828       ┆ 2018-12-26 ┆ 002415 ┆ … ┆ 1.10235e6 ┆ 33.2      ┆ 1.19      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2016-12-31 ┆ 9760      ┆ 2017-02-21 ┆ 002168 ┆ … ┆ 7200.0    ┆ 5.7       ┆ 0.087077  ┆ 194.4     │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2020-12-31 ┆ 5705      ┆ 2020-12-30 ┆ 300750 ┆ … ┆ 550000.0  ┆ null      ┆ null      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2018-12-31 ┆ 8044      ┆ 2019-01-14 ┆ 002557 ┆ … ┆ 39039.0   ┆ null      ┆ 0.77      ┆ null      │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [165]:
# 生成上一个报告期
con = con.with_columns(
    pl.col("report_date")
    .dt.offset_by("-3mo")          # 减去 3 个月
    .dt.month_end()             # 确保是月末日期
    .alias("last_report_date")        # 新列名，可根据需要改为 "report_date" 覆盖原列
)
con

shape: (94_393, 11)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ report_dat ┆ author_id ┆ con_infoda ┆ tick   ┆ … ┆ forecast_ ┆ forecast_ ┆ forecast_ ┆ last_repo │
│ e          ┆ ---       ┆ te         ┆ ---    ┆   ┆ roe       ┆ eps       ┆ pe        ┆ rt_date   │
│ ---        ┆ u32       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ datetime[μ ┆           ┆ datetime[μ ┆        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ datetime[ │
│ s]         ┆           ┆ s]         ┆        ┆   ┆           ┆           ┆           ┆ μs]       │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2027-12-31 ┆ 5430      ┆ 2025-12-18 ┆ 301397 ┆ … ┆ null      ┆ 1.53      ┆ null      ┆ 2027-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2017-12-31 ┆ 318       ┆ 2018-01-25 ┆ 601939 ┆ … ┆ 15.03     ┆ 0.98      ┆ null      ┆ 2017-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2026-12-31 ┆ 12902     ┆ 2025-09-30 ┆ 600406 ┆ … ┆ 17.5      ┆ 1.19      ┆ null      ┆ 2026-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2010-12-31 ┆ 10443     ┆ 2009-06-03 ┆ 002007 ┆ … ┆ null      ┆ 0.94      ┆ null      ┆ 2010-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2025-12-31 ┆ 11505     ┆ 2024-11-09 ┆ 688150 ┆ … ┆ 15.53     ┆ 0.8       ┆ 30.08     ┆ 2025-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ …          ┆ …         ┆ …          ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-12-31 ┆ 5335      ┆ 2025-10-30 ┆ 000333 ┆ … ┆ 20.4      ┆ 6.32      ┆ 11.7      ┆ 2026-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2018-12-31 ┆ 828       ┆ 2018-12-26 ┆ 002415 ┆ … ┆ 33.2      ┆ 1.19      ┆ null      ┆ 2018-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2016-12-31 ┆ 9760      ┆ 2017-02-21 ┆ 002168 ┆ … ┆ 5.7       ┆ 0.087077  ┆ 194.4     ┆ 2016-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2020-12-31 ┆ 5705      ┆ 2020-12-30 ┆ 300750 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2020-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
│ 2018-12-31 ┆ 8044      ┆ 2019-01-14 ┆ 002557 ┆ … ┆ null      ┆ 0.77      ┆ null      ┆ 2018-09-3 │
│ 00:00:00   ┆           ┆ 00:00:00   ┆        ┆   ┆           ┆           ┆           ┆ 0         │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 00:00:00  │
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [169]:
f_merge_con = f_merge2.select(['tick','report_date','sheet_infodate']).join(
    con, how='left',on=['tick','report_date'],suffix='_coninfo'
).join(
    f_merge2.select(['tick','report_date','sheet_infodate']),
    how='left',
    left_on=['tick','last_report_date'],
    right_on=['tick','report_date'],
    suffix="_last"
)
# 确保分析师预期发布，在两个发布日之间
f_merge_con = f_merge_con.filter( 
    (pl.col('con_infodate')>pl.col('sheet_infodate_last')) & (pl.col('con_infodate')<pl.col('sheet_infodate'))
)
f_merge_con

shape: (28_353, 13)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ sheet_info ┆ author_id ┆ … ┆ forecast_ ┆ forecast_ ┆ last_repo ┆ sheet_inf │
│ ---    ┆ e          ┆ date       ┆ ---       ┆   ┆ eps       ┆ pe        ┆ rt_date   ┆ odate_las │
│ str    ┆ ---        ┆ ---        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ t         │
│        ┆ datetime[μ ┆ datetime[μ ┆           ┆   ┆ f64       ┆ f64       ┆ datetime[ ┆ ---       │
│        ┆ s]         ┆ s]         ┆           ┆   ┆           ┆           ┆ μs]       ┆ datetime[ │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ μs]       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 2006-12-31 ┆ 2007-03-22 ┆ 8         ┆ … ┆ 0.7       ┆ null      ┆ 2006-09-3 ┆ 2006-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 6         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2007-12-31 ┆ 2008-03-20 ┆ 35        ┆ … ┆ 1.0       ┆ null      ┆ 2007-09-3 ┆ 2007-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 3         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2007-12-31 ┆ 2008-03-20 ┆ 25        ┆ … ┆ 1.151562  ┆ null      ┆ 2007-09-3 ┆ 2007-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 3         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2007-12-31 ┆ 2008-03-20 ┆ 31        ┆ … ┆ 1.15      ┆ null      ┆ 2007-09-3 ┆ 2007-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 3         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2007-12-31 ┆ 2008-03-20 ┆ 1         ┆ … ┆ 1.17      ┆ null      ┆ 2007-09-3 ┆ 2007-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 3         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 13763     ┆ … ┆ null      ┆ null      ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 3755      ┆ … ┆ 0.5       ┆ 203.62    ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 11725     ┆ … ┆ 0.46      ┆ 225.0     ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 1710      ┆ … ┆ 0.46      ┆ 213.72    ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 3253      ┆ … ┆ 0.46      ┆ 213.72    ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [170]:
key_cols = ["tick", "report_date"]

forecast_cols = [
    "forecast_or",
    "forecast_op",
    "forecast_np",
    "forecast_roe",
    "forecast_eps",
    "forecast_pe",
]

con_result = (
    f_merge_con
    .with_columns([
        pl.col(c).median().over(key_cols).alias(c)
        for c in forecast_cols
    ])
    .drop("author_id")   # 如果你的列名是 authorid / author_id，就改成实际列名
    .unique(
        subset=key_cols,
        keep="first",
        maintain_order=True,
    )
)

con_result = con_result.drop(['last_report_date','sheet_infodate_last','con_infodate'])
con_result

shape: (12_270, 12)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ sheet_info ┆ con_infod ┆ … ┆ forecast_ ┆ forecast_ ┆ last_repo ┆ sheet_inf │
│ ---    ┆ e          ┆ date       ┆ ate       ┆   ┆ eps       ┆ pe        ┆ rt_date   ┆ odate_las │
│ str    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ t         │
│        ┆ datetime[μ ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ datetime[ ┆ ---       │
│        ┆ s]         ┆ s]         ┆ μs]       ┆   ┆           ┆           ┆ μs]       ┆ datetime[ │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ μs]       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 2006-12-31 ┆ 2007-03-22 ┆ 2007-01-1 ┆ … ┆ 0.7       ┆ null      ┆ 2006-09-3 ┆ 2006-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 5         ┆   ┆           ┆           ┆ 0         ┆ 6         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2007-12-31 ┆ 2008-03-20 ┆ 2008-03-1 ┆ … ┆ 1.150781  ┆ null      ┆ 2007-09-3 ┆ 2007-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 7         ┆   ┆           ┆           ┆ 0         ┆ 3         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2008-12-31 ┆ 2009-03-20 ┆ 2008-10-2 ┆ … ┆ 0.19321   ┆ null      ┆ 2008-09-3 ┆ 2008-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 7         ┆   ┆           ┆           ┆ 0         ┆ 4         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2009-09-30 ┆ 2009-10-29 ┆ 2009-10-2 ┆ … ┆ 1.14      ┆ null      ┆ 2009-06-3 ┆ 2009-08-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 0         ┆   ┆           ┆           ┆ 0         ┆ 1         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 000001 ┆ 2009-12-31 ┆ 2010-03-12 ┆ 2010-01-3 ┆ … ┆ 1.515012  ┆ null      ┆ 2009-09-3 ┆ 2009-10-2 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 1         ┆   ┆           ┆           ┆ 0         ┆ 9         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 688981 ┆ 2020-12-31 ┆ 2021-04-01 ┆ 2020-12-2 ┆ … ┆ 0.47      ┆ 116.6     ┆ 2020-09-3 ┆ 2020-11-1 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 3         ┆   ┆           ┆           ┆ 0         ┆ 2         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2021-12-31 ┆ 2022-03-31 ┆ 2022-02-1 ┆ … ┆ 1.475     ┆ 37.0      ┆ 2021-09-3 ┆ 2021-11-1 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 1         ┆   ┆           ┆           ┆ 0         ┆ 2         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2022-12-31 ┆ 2023-03-29 ┆ 2023-02-1 ┆ … ┆ 1.56      ┆ 33.76     ┆ 2022-09-3 ┆ 2022-11-1 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 4         ┆   ┆           ┆           ┆ 0         ┆ 1         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2023-12-31 ┆ 2024-03-29 ┆ 2024-01-2 ┆ … ┆ 0.66      ┆ 67.6      ┆ 2023-09-3 ┆ 2023-11-1 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 4         ┆   ┆           ┆           ┆ 0         ┆ 0         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
│ 688981 ┆ 2024-12-31 ┆ 2025-03-28 ┆ 2025-02-1 ┆ … ┆ 0.46      ┆ 213.72    ┆ 2024-09-3 ┆ 2024-11-0 │
│        ┆ 00:00:00   ┆ 00:00:00   ┆ 2         ┆   ┆           ┆           ┆ 0         ┆ 8         │
│        ┆            ┆            ┆ 00:00:00  ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00  │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [222]:
final_merge = f_merge2.join(
    con_result, how='left', on=['tick','report_date']
)

final_merge = final_merge.with_columns(
    pl.col("report_date").dt.offset_by("-1y").alias("lyr_report_date")
).join(
    f_merge2, how='left', left_on=['tick','lyr_report_date'], right_on=['tick','report_date'], suffix='_lyr'
)
final_merge

shape: (262_049, 39)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ sheet_info ┆ basic_eps ┆ … ┆ total_ass ┆ net_opera ┆ roe_lyr   ┆ l2a_lyr   │
│ ---    ┆ e          ┆ date       ┆ ---       ┆   ┆ ets_lyr   ┆ te_cash_f ┆ ---       ┆ ---       │
│ str    ┆ ---        ┆ ---        ┆ decimal[3 ┆   ┆ ---       ┆ low_lyr   ┆ decimal[3 ┆ decimal[3 │
│        ┆ datetime[μ ┆ datetime[μ ┆ 8,4]      ┆   ┆ decimal[3 ┆ ---       ┆ 8,4]      ┆ 8,4]      │
│        ┆ s]         ┆ s]         ┆           ┆   ┆ 8,4]      ┆ decimal[3 ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆           ┆ 8,4]      ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 1998-06-30 ┆ 1998-08-26 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 1998-12-31 ┆ 1999-04-23 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 1999-06-30 ┆ 1999-07-17 ┆ null      ┆ … ┆ 348733722 ┆ 158155570 ┆ 0.1002    ┆ 0.8917    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 70.7500   ┆ 1.2300    ┆           ┆           │
│ 000001 ┆ 1999-12-31 ┆ 2000-04-19 ┆ null      ┆ … ┆ 393998586 ┆ 229109784 ┆ 0.2079    ┆ 0.9067    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 17.2600   ┆ 2.5500    ┆           ┆           │
│ 000001 ┆ 2000-06-30 ┆ 2000-07-26 ┆ null      ┆ … ┆ 387121129 ┆ 421788125 ┆ 0.0615    ┆ 0.8988    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 99.2300   ┆ .4400     ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ X25198 ┆ 2021-12-31 ┆ 2022-04-28 ┆ null      ┆ … ┆ 770973991 ┆ 210802095 ┆ 0.1401    ┆ 0.8037    │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆ 8.3000    ┆ .8100     ┆           ┆           │
│ X25202 ┆ 2014-03-31 ┆ 2014-04-30 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25202 ┆ 2014-06-30 ┆ 2014-08-22 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25202 ┆ 2014-09-30 ┆ 2014-10-20 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25216 ┆ 2023-06-30 ┆ 2023-08-31 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [223]:
# 计算yoy
yoys = [
    'basic_eps',
    'total_operating_revenue',
    'np_parent_company_owners',
    'net_operate_cash_flow',
    'roe','l2a','gpm','npm'
]
final_merge = final_merge.with_columns([
        ((pl.col(c)/pl.col(c+'_lyr').replace(0,None))-1).alias(c+'_yoy')
        for c in yoys
])

# 计算sue
final_merge = final_merge.with_columns([
    (pl.col('basic_eps')-pl.col('forecast_eps')).alias('eps_ue'),
    (pl.col('total_operating_revenue')-pl.col('forecast_or')).alias('or_ue'),
    (pl.col('net_profit')-pl.col('forecast_np')).alias('np_ue'),
    (pl.col('roe')-pl.col('forecast_roe')).alias('roe_ue')
])
ue_cols = ['eps_ue', 'or_ue', 'np_ue', 'roe_ue']
final_merge = final_merge.with_columns([
    pl.col(col).shift(1).rolling_std(window_size=12, min_periods=1, ddof=0).over('tick').alias(f'{col}_std')
    for col in ue_cols
]).with_columns([
    (pl.col(col) / pl.col(col+'_std').replace(0, None)).alias(col+'_sue')
    for col in ue_cols
])
final_merge

shape: (262_049, 59)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tick   ┆ report_dat ┆ sheet_info ┆ basic_eps ┆ … ┆ eps_ue_su ┆ or_ue_sue ┆ np_ue_sue ┆ roe_ue_su │
│ ---    ┆ e          ┆ date       ┆ ---       ┆   ┆ e         ┆ ---       ┆ ---       ┆ e         │
│ str    ┆ ---        ┆ ---        ┆ decimal[3 ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---       │
│        ┆ datetime[μ ┆ datetime[μ ┆ 8,4]      ┆   ┆ f64       ┆           ┆           ┆ f64       │
│        ┆ s]         ┆ s]         ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 000001 ┆ 1998-06-30 ┆ 1998-08-26 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 1998-12-31 ┆ 1999-04-23 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 1999-06-30 ┆ 1999-07-17 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 1999-12-31 ┆ 2000-04-19 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ 000001 ┆ 2000-06-30 ┆ 2000-07-26 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ X25198 ┆ 2021-12-31 ┆ 2022-04-28 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25202 ┆ 2014-03-31 ┆ 2014-04-30 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25202 ┆ 2014-06-30 ┆ 2014-08-22 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25202 ┆ 2014-09-30 ┆ 2014-10-20 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
│ X25216 ┆ 2023-06-30 ┆ 2023-08-31 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ 00:00:00   ┆ 00:00:00   ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [224]:
final_merge = final_merge.with_columns(
    pl.when(pl.col('report_date').dt.month()==3).then(pl.lit(1)).otherwise(0).alias('mask1'),
    pl.when(pl.col('report_date').dt.month()==6).then(pl.lit(1)).otherwise(0).alias('mask2'),
    pl.when(pl.col('report_date').dt.month()==9).then(pl.lit(1)).otherwise(0).alias('mask3'),
    pl.when(pl.col('report_date').dt.month()==12).then(pl.lit(1)).otherwise(0).alias('mask4'),
)
final_merge

shape: (262_049, 63)
┌────────┬───────────────┬─────────────────────┬───────────────┬───┬───────┬───────┬───────┬───────┐
│ tick   ┆ report_date   ┆ sheet_infodate      ┆ basic_eps     ┆ … ┆ mask1 ┆ mask2 ┆ mask3 ┆ mask4 │
│ ---    ┆ ---           ┆ ---                 ┆ ---           ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str    ┆ datetime[μs]  ┆ datetime[μs]        ┆ decimal[38,4] ┆   ┆ i32   ┆ i32   ┆ i32   ┆ i32   │
╞════════╪═══════════════╪═════════════════════╪═══════════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ 000001 ┆ 1998-06-30    ┆ 1998-08-26 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ 000001 ┆ 1998-12-31    ┆ 1999-04-23 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 1     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ 000001 ┆ 1999-06-30    ┆ 1999-07-17 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ 000001 ┆ 1999-12-31    ┆ 2000-04-19 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 1     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ 000001 ┆ 2000-06-30    ┆ 2000-07-26 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ …      ┆ …             ┆ …                   ┆ …             ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ X25198 ┆ 2021-12-31    ┆ 2022-04-28 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 1     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ X25202 ┆ 2014-03-31    ┆ 2014-04-30 00:00:00 ┆ null          ┆ … ┆ 1     ┆ 0     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ X25202 ┆ 2014-06-30    ┆ 2014-08-22 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ X25202 ┆ 2014-09-30    ┆ 2014-10-20 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
│ X25216 ┆ 2023-06-30    ┆ 2023-08-31 00:00:00 ┆ null          ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│        ┆ 00:00:00      ┆                     ┆               ┆   ┆       ┆       ┆       ┆       │
└────────┴───────────────┴─────────────────────┴───────────────┴───┴───────┴───────┴───────┴───────┘

In [ ]:
final = final_merge.with_columns([
    ((pl.col("sheet_infodate") - pl.col("report_date")).dt.total_days().abs()+ 1).log().alias("log_distance"),
])

In [226]:
final = final.drop(['report_date','lyr_report_date','sheet_infodate_lyr'])

In [227]:
raw_feat_names = [
    'basic_eps_yoy',
    'total_operating_revenue_yoy',
    'np_parent_company_owners_yoy',
    'net_operate_cash_flow_yoy',
    'roe_yoy','l2a_yoy','gpm_yoy','npm_yoy',
    'eps_ue_sue', 'or_ue_sue', 'np_ue_sue', 'roe_ue_sue',
    'log_distance'
]
for feat_name in raw_feat_names:
    feat = final.pivot(index='sheet_infodate',columns='tick',values=feat_name).to_pandas().set_index('sheet_infodate').reindex(index=dates,columns=ticks).fillna(0)
    print(feat_name)
    feat.to_numpy().astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/{feat_name}.bin')

basic_eps_yoy
total_operating_revenue_yoy
np_parent_company_owners_yoy
net_operate_cash_flow_yoy
roe_yoy
l2a_yoy
gpm_yoy
npm_yoy
eps_ue_sue
or_ue_sue
np_ue_sue
roe_ue_sue
log_distance

In [ ]:
extra_feat_names = ['pct_20rollstd','pct_20rollmean','turnover_20rollstd','turnover_20rollmean']

for feat_name in ['pct','turnover']:
    feat = np.memmap(f'/data/xujiayi/xjy/d_field/{feat_name}.bin', dtype=float, shape=(len(dates),len(ticks)), mode='r')
    feat_20rollmean = Calculator.rolling_nanmean(feat, 20)
    feat_20rollmean = Processor.cross_standardize(feat_20rollmean)
    feat_20rollstd = Calculator.rolling_nanstd(feat, 20)
    feat_20rollstd = Processor.cross_standardize(feat_20rollstd)
    
    feat_20rollmean.astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/{feat_name}_20rollmean.bin')
    feat_20rollstd.astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/{feat_name}_20rollstd.bin')

In [232]:
event_mask = []
for event in ['mask1','mask2','mask3','mask4']:
     mask = final.pivot(index='sheet_infodate',columns='tick',values=event).to_pandas().set_index('sheet_infodate').reindex(index=dates,columns=ticks).fillna(0)
     mask = mask.to_numpy()
     mask.astype(int).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/{event}.bin')
     event_mask.append(mask)
event_mask = np.stack(event_mask, axis=-1)
event_mask.astype(int).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/event_mask.bin')

In [233]:
ms = []
for e in ['mask1','mask2','mask3','mask4']:
    mask = np.memmap(
        f'/data/xujiayi/xjy/research_factors/model_specific/ered/{e}.bin',
        mode='r', shape=(len(dates),len(ticks)), dtype=int
    )
    ms.append(mask)

event_vec = []
for feat_name in raw_feat_names+extra_feat_names:
    feat = np.memmap(
        f'/data/xujiayi/xjy/research_factors/model_specific/ered/{feat_name}.bin',
        mode='r', shape=(len(dates),len(ticks)), dtype=float            
    )
    for mask in ms:
        feat = np.where(mask, feat, 0)
        event_vec.append(feat)
event_vec = np.stack(event_vec, axis=-1).reshape(len(dates), len(ticks), -1, 4).transpose(0,1,3,2)
event_vec.shape

(4376, 5436, 4, 17)

In [234]:
event_vec.astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_specific/ered/event_vec.bin')