In [1]:
import os
import sys

# 将项目根目录加入 sys.path（根据实际情况修改路径）
project_root = os.path.abspath('..')   # 或 os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 然后绝对导入
from utils import Processor, Calculator

In [2]:
import os
import polars as pl
import numpy as np
import torch
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time
from sqlalchemy import create_engine
import pymssql
from typing import List, Dict

import warnings
warnings.filterwarnings('ignore')

In [3]:
T,N = 3400, 5422
start_dt = '2008-01-01'     
end_dt = '2025-12-31'

ROOT = '/data/xujiayi/end2end/'

JY_CONFIG = {
    "server": '10.10.0.102',
    "user": 'jydbReader',
    "password": 'jy@9043!Reader',
    "database": 'jydb',
    "charset": 'cp936'
}
JY_CONN = pymssql.connect(**JY_CONFIG)

STR_CONN = create_engine('mysql+pymysql://QuantReader:Quant%40Reader%21zsfund.com@10.10.6.101:9030/HighFrequency')

In [4]:
dates = np.load('/data/xujiayi/end2end/axis/dates.npy', allow_pickle=True)
ticks = np.load('/data/xujiayi/end2end/axis/ticks.npy', allow_pickle=True)

close = np.memmap('/data/xujiayi/end2end/d_field/close.bin',dtype=float,shape=(len(dates),len(ticks)),mode='r')
nan_mask = np.isnan(close)

industry = np.memmap('/data/xujiayi/xjy/mask/industry.bin', shape=(len(dates),len(ticks)), mode='r', dtype=float)

##### 获取季度财报数据

In [5]:
sql_f = f'''select
                C.SecuCode as "tick",
                A.EndDate as "report_date",
                A.InfoPublDate as "date",
                A.ROETTM,
                A.ROICTTM,
                A.GrossIncomeRatioTTM,
                A.NetProfitRatioTTM,
                A.PeriodCostsRateTTM,
                A.AdminiExpenseRateTTM,
                A.TotalAssetTRateTTM,
                A.ARTRate,
                A.InventoryTRate,
                A.DebtAssetsRatio,
                A.LongDebtRatio,
                A.NPParentCompanyCutYOY,
                A.TotalAssetGrowRate,
                A.NetOperateCashFlowYOY,
                A.NOCFToOperatingNITTM,
                A.SaleServiceCashToORTTM,
                A.OperCashInToAsset,
                A.FixAssetRatio,
                A.IntangibleAssetRatio,
                A.DividendPaidRatio,
                A.RetainedEarningRatio

            from LC_MainIndexNew A
            left join SecuMain C
            on A.CompanyCode = C.CompanyCode
            where A.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1

            union all

            select
                C.SecuCode as "tick",
                B.EndDate as "report_date",
                B.InfoPublDate as "date",
                B.ROETTM,
                B.ROICTTM,
                B.GrossIncomeRatioTTM,
                B.NetProfitRatioTTM,
                B.PeriodCostsRateTTM,
                B.AdminiExpenseRateTTM,
                B.TotalAssetTRateTTM,
                B.ARTRate,
                B.InventoryTRate,
                B.DebtAssetsRatio,
                B.LongDebtRatio,
                B.NPParentCompanyCutYOY,
                B.TotalAssetGrowRate,
                B.NetOperateCashFlowYOY,
                B.NOCFToOperatingNITTM,
                B.SaleServiceCashToORTTM,
                B.OperCashInToAsset,
                B.FixAssetRatio,
                B.IntangibleAssetRatio,
                B.DividendPaidRatio,
                B.RetainedEarningRatio

            from LC_STIBMainIndex B
            left join SecuMain C
            on B.CompanyCode = C.CompanyCode
            where B.InfoPublDate <= '{end_dt}'
                and C.SecuMarket in (83,90)
                and C.SecuCategory=1
                and B.IfMerged=1
                and B.IfAdjusted=2
        '''

f = pd.read_sql(sql_f, JY_CONN)
f = pl.from_pandas(f)
f = f.sort(["tick", "report_date", "date"]).filter(pl.col('tick').is_in(ticks)).filter(pl.col('report_date')>=pl.datetime(2007,12,31))
f = f.unique(subset=["tick", "date"], keep="last").unique(subset=["tick", "report_date"], keep="first")

In [6]:
feat_cols = [
    'ROETTM', 'ROICTTM', 'GrossIncomeRatioTTM', 'NetProfitRatioTTM',
    'PeriodCostsRateTTM', 'AdminiExpenseRateTTM',
    'TotalAssetTRateTTM', 'ARTRate', 'InventoryTRate',
    'DebtAssetsRatio', 'LongDebtRatio', 
    'NPParentCompanyCutYOY', 'TotalAssetGrowRate', 'NetOperateCashFlowYOY',
    'NOCFToOperatingNITTM', 'SaleServiceCashToORTTM', 'OperCashInToAsset',
    'FixAssetRatio', 'IntangibleAssetRatio',
    #'DividendPaidRatio', 'RetainedEarningRatio'
]
f = f.select(['tick', 'date'] + feat_cols)

calendar = pl.DataFrame({'trade_date':dates})
df = f.sort('date').join_asof(calendar, left_on='date', right_on='trade_date', strategy='forward').sort('tick','date')
df = df.sort(['tick', 'trade_date', 'date']).unique(subset=['tick', 'trade_date'], keep='last')

In [7]:
date2idx = {d:i for i,d in enumerate(dates)}
tick2idx = {t:i for i,t in enumerate(ticks)}

date_idx = np.array([date2idx.get(x, -1) for x in df["trade_date"].to_list()], dtype=np.int32)
tick_idx = np.array([tick2idx.get(x, -1) for x in df["tick"].to_list()], dtype=np.int32)

df = df.with_columns([
    pl.Series("date_idx", date_idx),
    pl.Series("tick_idx", tick_idx),
]).filter(
    pl.col('date_idx').is_not_null()
)

In [8]:
ind = industry[df["date_idx"].to_numpy(), df["tick_idx"].to_numpy()]
df = df.with_columns(pl.Series("industry", ind))

ignore = {"tick","report_date","date","trade_date","tick_idx","date_idx","industry"}
features = [c for c in df.columns if c not in ignore]
for f in features:

    # 行业中值填补缺失值
    industry_med = pl.col(f).median().over(["trade_date", "industry"])
    df = df.with_columns(
        pl.when(pl.col(f).is_null() & pl.col('industry').is_not_null())
        .then(industry_med)
        .otherwise(pl.col(f))
        .alias(f)
    )
    # 去极值
    market_med = pl.col(f).median().over("trade_date")
    mad = (
        (pl.col(f)-market_med)
        .abs()
        .median()
        .over("trade_date")
    )
    upper = market_med + 3 * 1.4826 * mad
    lower = market_med - 3 * 1.4826 * mad
    df = df.with_columns(
        pl.when(pl.col(f) > upper)
        .then(upper)
        .when(pl.col(f) < lower)
        .then(lower)
        .otherwise(pl.col(f))
        .alias(f)
    )
    # 截面标准化
    mean = pl.col(f).mean().over("trade_date")
    std = pl.col(f).std().over("trade_date")
    standardized = pl.when(std == 0).then(0.0)  .otherwise((pl.col(f) - mean) / std)
    df = df.with_columns(standardized.alias(f))

In [42]:
for feat_name in features:    
    feat = df.select(['tick','trade_date',feat_name]).sort(['tick','trade_date'])
    feat = feat.pivot(index='trade_date', columns='tick', values=feat_name)
    feat = feat.to_pandas().set_index('trade_date').reindex(index=dates).reindex(columns=ticks)
    feat.to_numpy().astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_input/ered_v2/raw/{feat_name}.bin')

    feat_fill = feat.ffill()
    feat_fill[nan_mask] = np.nan
    feat_fill = feat_fill.ffill()
    feat_fill.to_numpy().astype(float).tofile(f'/data/xujiayi/xjy/research_factors/model_input/ered_v2/ffill/{feat_name}.bin')

#### 处理成ered格式

In [43]:
dff = df.select(['tick','date','trade_date','tick_idx','date_idx']).sort(['tick','trade_date'])
dff = dff.drop('date').rename({'trade_date':'date'})
dff

shape: (226_648, 4)
┌────────┬─────────────────────┬──────────┬──────────┐
│ tick   ┆ date                ┆ tick_idx ┆ date_idx │
│ ---    ┆ ---                 ┆ ---      ┆ ---      │
│ str    ┆ datetime[μs]        ┆ i32      ┆ i32      │
╞════════╪═════════════════════╪══════════╪══════════╡
│ 000001 ┆ 2008-03-20 00:00:00 ┆ 0        ┆ 51       │
│ 000001 ┆ 2008-04-24 00:00:00 ┆ 0        ┆ 75       │
│ 000001 ┆ 2008-08-21 00:00:00 ┆ 0        ┆ 157      │
│ 000001 ┆ 2008-10-24 00:00:00 ┆ 0        ┆ 197      │
│ 000001 ┆ 2009-03-20 00:00:00 ┆ 0        ┆ 295      │
│ …      ┆ …                   ┆ …        ┆ …        │
│ 688981 ┆ 2024-11-08 00:00:00 ┆ 5435     ┆ 4095     │
│ 688981 ┆ 2025-03-28 00:00:00 ┆ 5435     ┆ 4188     │
│ 688981 ┆ 2025-05-09 00:00:00 ┆ 5435     ┆ 4214     │
│ 688981 ┆ 2025-08-29 00:00:00 ┆ 5435     ┆ 4293     │
│ 688981 ┆ 2025-11-14 00:00:00 ┆ 5435     ┆ 4342     │
└────────┴─────────────────────┴──────────┴──────────┘

In [46]:
d = dff["date_idx"].to_numpy()
t = dff["tick_idx"].to_numpy()

for feat_name in feat_cols+['pct_20rollstd','pct_20rollmean','turnover_20rollstd','turnover_20rollmean']:
    feat = np.memmap(f'/data/xujiayi/xjy/research_factors/model_input/ered_v2/ffill/{feat_name}.bin',mode='r',shape=(len(dates),len(ticks)),dtype=float)
    val = feat[d,t]
    dff = dff.with_columns(pl.Series(feat_name, val))

dff

shape: (226_648, 27)
┌────────┬────────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ tick   ┆ date       ┆ tick_idx ┆ date_idx ┆ … ┆ pct_20roll ┆ pct_20roll ┆ turnover_2 ┆ turnover_ │
│ ---    ┆ ---        ┆ ---      ┆ ---      ┆   ┆ std        ┆ mean       ┆ 0rollstd   ┆ 20rollmea │
│ str    ┆ datetime[μ ┆ i32      ┆ i32      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ n         │
│        ┆ s]         ┆          ┆          ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│        ┆            ┆          ┆          ┆   ┆            ┆            ┆            ┆ f64       │
╞════════╪════════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 000001 ┆ 2008-03-20 ┆ 0        ┆ 51       ┆ … ┆ 0.035228   ┆ -0.03978   ┆ -0.260754  ┆ -0.325548 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 000001 ┆ 2008-04-24 ┆ 0        ┆ 75       ┆ … ┆ -0.067061  ┆ 0.139837   ┆ -0.477472  ┆ -0.2628   │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 000001 ┆ 2008-08-21 ┆ 0        ┆ 157      ┆ … ┆ -0.641632  ┆ 1.165629   ┆ -0.514051  ┆ -0.580024 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 000001 ┆ 2008-10-24 ┆ 0        ┆ 197      ┆ … ┆ 0.947466   ┆ -0.059645  ┆ -0.446407  ┆ -0.380687 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 000001 ┆ 2009-03-20 ┆ 0        ┆ 295      ┆ … ┆ 0.088471   ┆ 1.053865   ┆ -0.679033  ┆ -0.929988 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ …      ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 688981 ┆ 2024-11-08 ┆ 5435     ┆ 4095     ┆ … ┆ 0.373259   ┆ 0.276714   ┆ 0.148968   ┆ 0.380164  │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 688981 ┆ 2025-03-28 ┆ 5435     ┆ 4188     ┆ … ┆ -0.213388  ┆ -0.169897  ┆ -0.652125  ┆ -0.497805 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 688981 ┆ 2025-05-09 ┆ 5435     ┆ 4214     ┆ … ┆ -0.273521  ┆ -0.740365  ┆ -0.388062  ┆ -0.514663 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 688981 ┆ 2025-08-29 ┆ 5435     ┆ 4293     ┆ … ┆ 1.307145   ┆ 1.321912   ┆ 0.487208   ┆ -0.078995 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
│ 688981 ┆ 2025-11-14 ┆ 5435     ┆ 4342     ┆ … ┆ 0.056547   ┆ -0.45635   ┆ -0.405264  ┆ -0.104088 │
│        ┆ 00:00:00   ┆          ┆          ┆   ┆            ┆            ┆            ┆           │
└────────┴────────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [49]:
all_x = []
all_eff_idx = []
tick_ptr = [0]
for tick in ticks:
    group = df.filter(pl.col('tick')==tick).sort('trade_date')
    if len(group)==0:
        tick_ptr.append(tick_ptr[-1])
        continue
    eff_idx = group['date_idx'].to_numpy()
    feats = group[feat_cols].to_numpy()

    all_x.append(feats)
    all_eff_idx.append(eff_idx)
    tick_ptr.append(tick_ptr[-1]+len(feats))

if len(all_x) == 0:
    final_x = np.zeros((0, len(feat_cols)), dtype=np.float32)
    final_eff_idx = np.zeros((0,), dtype=np.int64)
else:
    final_x = np.vstack(all_x)
    final_eff_idx = np.hstack(all_eff_idx)
tick_ptr = np.array(tick_ptr, dtype=np.int64)

In [50]:
from pathlib import Path
out_path = Path('/data/xujiayi/xjy/research_factors/model_input/ered_v2/')

np.save(out_path / 'event_x.npy', final_x)
np.save(out_path / 'event_effective_idx.npy', final_eff_idx)
np.save(out_path / 'event_tick_ptr.npy', tick_ptr)

In [51]:
import json

metadata = {
    "event_dim": len(feat_cols),
    "num_events": int(len(final_eff_idx)),
    "num_ticks": int(len(ticks)),
    "max_events_config": 8,
    "config": {
        "max_events": 8,
    }
}
with open(out_path / 'metadata.json', 'w', encoding='utf-8') as f:
    json.dump(metadata, f, indent=2, ensure_ascii=False)